"""No file in the tree may tell a reader to install a stack that never ran.

Two files used to. ``requirements.lock`` and ``configs/environment.yml`` both
pinned numpy 1.26.4 -- the version ``ENVIRONMENT.json`` records as unusable
here, because it segfaults on import -- while ``requirements.txt`` and the
measured record said 2.5.1. Nothing read the two stale files: not the Makefile,
not CI, not any tool in the repository. That is exactly why they survived. The
audit only ever compared the record against ``requirements.txt``, so the
contradiction sat in the tree for as long as it took someone to open it.

They are deleted. These tests are what stops the next one, and they check that
the gate bites rather than that the files are gone, because a gate nobody has
seen fail is not evidence of anything.
"""
from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))

import emit_environment as env  # noqa: E402

MEASURED = {"numpy": "2.5.1", "scipy": "1.17.1"}


def _pins(filename: str, body: str) -> list[str]:
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / filename
        path.write_text(body)
        return env._rival_pins(MEASURED, [path])


class TestTheTreeAgreesWithTheMeasurement(unittest.TestCase):
    def test_no_committed_file_contradicts_the_measured_stack(self) -> None:
        problems = env._rival_pins(env.build()["packages"])
        self.assertEqual(
            problems, [],
            "a dependency declaration in the tree contradicts the stack that "
            "produced the numbers:\n  " + "\n  ".join(problems))

    def test_the_deleted_rivals_have_not_come_back(self) -> None:
        for name in ("requirements.lock", "configs/environment.yml"):
            self.assertFalse(
                (ROOT / name).exists(),
                f"{name} was removed because it pinned a numpy that segfaults "
                f"here and nothing read it; if such a file is needed again it "
                f"has to be generated by tools/emit_environment.py, not "
                f"hand-written beside the measurement")


class TestTheGateBites(unittest.TestCase):
    """Plant each contradiction the deleted files carried; require a report."""

    def test_a_pip_pin_that_disagrees_is_caught(self) -> None:
        found = _pins("requirements.lock", "numpy==1.26.4\n")
        self.assertEqual(len(found), 1, found)
        self.assertIn("1.26.4", found[0])
        self.assertIn("2.5.1", found[0])

    def test_a_conda_pin_that_disagrees_is_caught(self) -> None:
        # configs/environment.yml used a single '=', which a pip-shaped parser
        # would have walked straight past.
        found = _pins("environment.yml",
                      "dependencies:\n  - python=3.12\n  - numpy=1.26.4\n")
        self.assertEqual(len(found), 1, found)
        self.assertIn("1.26.4", found[0])

    def test_a_lower_bound_the_measured_stack_fails_is_caught(self) -> None:
        found = _pins("constraints.txt", "scipy>=2.0\n")
        self.assertEqual(len(found), 1, found)
        self.assertIn("1.17.1", found[0])


class TestTheGateDoesNotCryWolf(unittest.TestCase):
    """A gate with false positives is a gate that gets switched off."""

    def test_a_lower_bound_the_stack_satisfies_is_allowed(self) -> None:
        # pyproject says numpy>=2.0, which is a statement about what the code
        # needs, not a claim about what produced the numbers.
        self.assertEqual(
            _pins("pyproject.toml", 'dependencies = ["numpy>=2.0"]\n'), [])

    def test_a_bad_pin_quoted_in_a_comment_is_not_an_offence(self) -> None:
        # requirements.txt and pyproject.toml both discuss 1.26.4 in prose, to
        # warn the reader off it. Reporting the warning as the fault would
        # force the explanation to be deleted.
        self.assertEqual(_pins(
            "requirements.txt",
            "# numpy==1.26.4 segfaults on import here and is not usable\n"
            "numpy==2.5.1\n"), [])

    def test_an_exact_pin_that_agrees_is_allowed(self) -> None:
        self.assertEqual(_pins("constraints.txt", "numpy==2.5.1\n"), [])


if __name__ == "__main__":
    unittest.main()
