#!/usr/bin/env python3
"""The P2Rank archive must cover every scored unit, and its checksums must hold.

P2Rank is the strongest competitor in the table, and every number reported for
it is a transformation of two CSV files that P2Rank writes into a temporary
directory and then forgets. Those files are archived, together with the command,
the tool version, the JVM banner and a SHA-256 of each file. This gate is what
makes that archive worth anything: it checks that the archive covers exactly the
units the telemetry claims were scored, that every recorded digest still matches
the bytes on disk, and that the provenance fields are populated rather than
present-and-empty.

Three failures this catches, all of which have occurred in some form here:
an archive written by a run that died halfway, so it covers 135 of 192 units and
nothing says so; an archive whose CSVs were regenerated by a later run while the
digests were not; and provenance fields that exist in the schema and are null,
which is how ``env_sha`` sat empty in every telemetry row for months.

A fourth is checked here because it is the one a reviewer raised first, and
because intact checksums say nothing about it: an archive can be complete and
unaltered while the baseline actually evaluated is a transformation of it. An
earlier revision of this project scored P2Rank by taking its top five pocket
centres, calling every residue within 6 A of one of them positive, and giving it
the reciprocal of the pocket rank as its score -- discarding the per-residue
probability that P2Rank itself emits. That harness reported P2Rank at 0.620
ROC-AUC against a published 0.81, and the paper drew a conclusion from the gap.
So this gate reads the archived ``*_residues.csv`` and requires that the scores
we evaluated *are* P2Rank's ``probability`` column and that our positive calls
*are* its own ``pocket != 0``, unit by unit and value by value.

Usage: PYTHONPATH=src python3.12 tools/check_p2rank_archive.py
"""
from __future__ import annotations

import csv
import hashlib
import io
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ARCHIVE = ROOT / "results/cryptobench_official/p2rank_raw"
TELEMETRY = ROOT / "results/cryptobench_official/TELEMETRY.json"
PREDICTIONS = ROOT / "results/cryptobench_official/predictions/p2rank.json"
REQUIRED = ("command", "tool_version", "jvm", "file_sha256")
# The column P2Rank calls its per-residue answer. Scoring the baseline off any
# other column, or off the pocket geometry, is a different baseline.
NATIVE_SCORE_COLUMN = "probability"


def _resnum(label: str) -> int | None:
    """P2Rank's residue_label, which carries an insertion code where one exists."""
    digits = ""
    negative = False
    for ch in reversed(label.strip()):
        if ch.isdigit():
            digits = ch + digits
        elif digits:
            negative = ch == "-"
            break
    if not digits:
        return None
    return -int(digits) if negative else int(digits)


def _native_output(csv_path: Path, chain: str) -> tuple[dict[int, float], set[int]]:
    """P2Rank's own per-residue probability and positive call, for one chain."""
    rows = list(csv.reader(io.StringIO(csv_path.read_text())))
    header = [h.strip() for h in rows[0]]
    i_chain = header.index("chain")
    i_label = header.index("residue_label")
    i_score = header.index(NATIVE_SCORE_COLUMN)
    i_pocket = header.index("pocket")
    scores: dict[int, float] = {}
    positive: set[int] = set()
    for row in rows[1:]:
        if not row or row[i_chain].strip() != chain:
            continue
        num = _resnum(row[i_label])
        if num is None:
            continue
        # Same merge rule as the adapter: labels differing only in an insertion
        # code name one slot, and the slot takes the strongest call in it.
        value = float(row[i_score])
        scores[num] = max(scores[num], value) if num in scores else value
        if int(row[i_pocket]) != 0:
            positive.add(num)
    return scores, positive


def _faithfulness_problems() -> list[str]:
    """Did we evaluate P2Rank's answer, or our own rewriting of it?"""
    if not PREDICTIONS.is_file():
        return [f"MISSING {PREDICTIONS.relative_to(ROOT)}: nothing records the "
                f"per-residue scores the P2Rank numbers were computed from"]
    units = json.loads(PREDICTIONS.read_text())["units"]
    problems: list[str] = []
    compared = 0
    for unit, pred in sorted(units.items()):
        csv_path = ARCHIVE / unit / "rec.pdb_residues.csv"
        if not csv_path.is_file():
            continue
        chain = unit.rsplit("_", 1)[-1]
        native, native_positive = _native_output(csv_path, chain)
        ours = {int(k): float(v) for k, v in (pred.get("residue_scores") or {}).items()}
        if not ours:
            problems.append(f"{unit}: no per-residue scores were kept")
            continue
        shared = sorted(set(ours) & set(native))
        wrong = [k for k in shared if abs(ours[k] - native[k]) > 1e-9]
        if wrong:
            k = wrong[0]
            problems.append(
                f"{unit}: {len(wrong)} of {len(shared)} residue scores are not "
                f"P2Rank's {NATIVE_SCORE_COLUMN} (residue {k}: we evaluated "
                f"{ours[k]!r}, P2Rank emitted {native[k]!r})")
        ours_positive = {int(r) for r in (pred.get("residue_positive") or [])}
        theirs = native_positive & set(ours)
        if ours_positive != theirs:
            problems.append(
                f"{unit}: the positive call is not P2Rank's own "
                f"({len(ours_positive)} residues called here, "
                f"{len(theirs)} assigned to a pocket by P2Rank)")
        compared += 1
    if not compared and not problems:
        problems.append("no unit could be compared against its archived CSV")
    return problems


def _sha256(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> int:
    if not TELEMETRY.exists():
        print(f"MISSING {TELEMETRY.relative_to(ROOT)}")
        return 1
    tel = json.loads(TELEMETRY.read_text())
    rows = tel["rows"] if isinstance(tel, dict) and "rows" in tel else tel
    scored = {r["unit_id"] for r in rows
              if r["method"] == "p2rank" and r.get("status") == "OK"}
    if not scored:
        print("no P2Rank rows in the telemetry; nothing to audit")
        return 0

    if not ARCHIVE.exists():
        print(f"MISSING {ARCHIVE.relative_to(ROOT)}: P2Rank was scored on "
              f"{len(scored)} units but no raw output was kept")
        return 1

    problems: list[str] = []
    present = {p.name for p in ARCHIVE.iterdir() if p.is_dir()}
    missing = sorted(scored - present)
    extra = sorted(present - scored)
    if missing:
        problems.append(f"{len(missing)} scored units have no archive "
                        f"(first: {', '.join(missing[:5])})")
    if extra:
        problems.append(f"{len(extra)} archived units are not in the telemetry "
                        f"(first: {', '.join(extra[:5])})")

    checked = 0
    for unit in sorted(scored & present):
        d = ARCHIVE / unit
        run = d / "run.json"
        if not run.is_file():
            problems.append(f"{unit}: no run.json, so nothing records what "
                            f"produced these files")
            continue
        doc = json.loads(run.read_text())
        for field in REQUIRED:
            if not doc.get(field):
                problems.append(f"{unit}: run.json has no {field}")
        for name, digest in (doc.get("file_sha256") or {}).items():
            f = d / name
            if not f.is_file():
                problems.append(f"{unit}: {name} recorded but absent")
                continue
            actual = _sha256(f)
            if actual != digest:
                problems.append(f"{unit}: {name} digest mismatch "
                                f"({digest[:12]} recorded, {actual[:12]} on disk)")
            checked += 1
        for needed in ("_residues.csv",):
            if not any(p.name.endswith(needed) for p in d.iterdir()):
                problems.append(f"{unit}: no *{needed}, which is the file every "
                                f"reported P2Rank number is derived from")

    problems.extend(_faithfulness_problems())

    if problems:
        print(f"P2Rank archive audit FAILED ({len(problems)} problems):")
        for p in problems[:25]:
            print(f"  - {p}")
        if len(problems) > 25:
            print(f"  ... and {len(problems) - 25} more")
        print("  regenerate: PYTHONPATH=src python3.12 "
              "tools/run_cryptobench_apo.py --dataset official "
              "--methods p2rank --merge")
        return 1

    sample = json.loads((ARCHIVE / sorted(scored)[0] / "run.json").read_text())
    print(f"P2Rank archive complete: {len(scored)} units, {checked} files, "
          f"every recorded digest matches")
    print(f"  p2rank {sample['tool_version']} under {sample['jvm']}")
    print(f"  every evaluated score is P2Rank's own {NATIVE_SCORE_COLUMN} column "
          f"and every positive call is its own pocket assignment")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
