#!/usr/bin/env python3
"""The P2Rank archive must cover every scored unit, and its checksums must hold.

P2Rank is the strongest competitor in the table, and every number reported for
it is a transformation of two CSV files that P2Rank writes into a temporary
directory and then forgets. Those files are archived, together with the command,
the tool version, the JVM banner and a SHA-256 of each file. This gate is what
makes that archive worth anything: it checks that the archive covers exactly the
units the telemetry claims were scored, that every recorded digest still matches
the bytes on disk, and that the provenance fields are populated rather than
present-and-empty.

Three failures this catches, all of which have occurred in some form here:
an archive written by a run that died halfway, so it covers 135 of 192 units and
nothing says so; an archive whose CSVs were regenerated by a later run while the
digests were not; and provenance fields that exist in the schema and are null,
which is how ``env_sha`` sat empty in every telemetry row for months.

Usage: PYTHONPATH=src python3.12 tools/check_p2rank_archive.py
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ARCHIVE = ROOT / "results/cryptobench_official/p2rank_raw"
TELEMETRY = ROOT / "results/cryptobench_official/TELEMETRY.json"
REQUIRED = ("command", "tool_version", "jvm", "file_sha256")


def _sha256(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> int:
    if not TELEMETRY.exists():
        print(f"MISSING {TELEMETRY.relative_to(ROOT)}")
        return 1
    tel = json.loads(TELEMETRY.read_text())
    rows = tel["rows"] if isinstance(tel, dict) and "rows" in tel else tel
    scored = {r["unit_id"] for r in rows
              if r["method"] == "p2rank" and r.get("status") == "OK"}
    if not scored:
        print("no P2Rank rows in the telemetry; nothing to audit")
        return 0

    if not ARCHIVE.exists():
        print(f"MISSING {ARCHIVE.relative_to(ROOT)}: P2Rank was scored on "
              f"{len(scored)} units but no raw output was kept")
        return 1

    problems: list[str] = []
    present = {p.name for p in ARCHIVE.iterdir() if p.is_dir()}
    missing = sorted(scored - present)
    extra = sorted(present - scored)
    if missing:
        problems.append(f"{len(missing)} scored units have no archive "
                        f"(first: {', '.join(missing[:5])})")
    if extra:
        problems.append(f"{len(extra)} archived units are not in the telemetry "
                        f"(first: {', '.join(extra[:5])})")

    checked = 0
    for unit in sorted(scored & present):
        d = ARCHIVE / unit
        run = d / "run.json"
        if not run.is_file():
            problems.append(f"{unit}: no run.json, so nothing records what "
                            f"produced these files")
            continue
        doc = json.loads(run.read_text())
        for field in REQUIRED:
            if not doc.get(field):
                problems.append(f"{unit}: run.json has no {field}")
        for name, digest in (doc.get("file_sha256") or {}).items():
            f = d / name
            if not f.is_file():
                problems.append(f"{unit}: {name} recorded but absent")
                continue
            actual = _sha256(f)
            if actual != digest:
                problems.append(f"{unit}: {name} digest mismatch "
                                f"({digest[:12]} recorded, {actual[:12]} on disk)")
            checked += 1
        for needed in ("_residues.csv",):
            if not any(p.name.endswith(needed) for p in d.iterdir()):
                problems.append(f"{unit}: no *{needed}, which is the file every "
                                f"reported P2Rank number is derived from")

    if problems:
        print(f"P2Rank archive audit FAILED ({len(problems)} problems):")
        for p in problems[:25]:
            print(f"  - {p}")
        if len(problems) > 25:
            print(f"  ... and {len(problems) - 25} more")
        print("  regenerate: PYTHONPATH=src python3.12 "
              "tools/run_cryptobench_apo.py --dataset official "
              "--methods p2rank --merge")
        return 1

    sample = json.loads((ARCHIVE / sorted(scored)[0] / "run.json").read_text())
    print(f"P2Rank archive complete: {len(scored)} units, {checked} files, "
          f"every recorded digest matches")
    print(f"  p2rank {sample['tool_version']} under {sample['jvm']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
