#!/usr/bin/env python3
"""Draw the training-fold architecture findings, and nothing from the test fold.

Why this is a separate generator
--------------------------------
``make_official_figures.py`` says in its first line that it draws the
official-fold comparison and nothing else, and that sentence is there because a
figure drawn from the wrong population sat in this repository for weeks being
read faster than the text that would have corrected it. These figures are drawn
from cluster-disjoint halves of the **training** fold. Putting them in that
generator would make one file that draws from two populations, and the next
person to add a panel would have to work out which they were in.

What is drawn, and why these two
--------------------------------
Figure A1, per-unit ROC-AUC against the number of cryptic residues in the unit.
Eight readout parameters and five wire families were swept in this repository
and every one of them was scored by a mean over units. That summary hides what
this panel shows at a glance: the deployed field scores 0.5991 on the 188 units
with fewer than ten cryptic residues and 0.8766 on the 201 with more than
twenty-two, and 87 units score below one half. The strip of points below the
0.5 line is the population that a threshold metric is destroyed by, which is
where the withdrawn F1 and MCC claims went.

Figure A2, the spatial gate swept per stratum, with the deployed radius marked.
It carries two things the text needs. The deployed ``r=18`` is not the best
radius for any stratum, and it is the worst of thirteen arms for the smallest.
And the improvement from ``r=14`` is the same size in every stratum, which is
what rules out the reading this sweep was launched to test -- that the optimum
radius rises with pocket size -- and makes it a better global constant instead.

No image carries a title. The descriptive text is emitted from the same
artifacts the plots are drawn from, into ARCHITECTURE_FIGURE_PROVENANCE.json and
into the README block, so a caption stating a unit count is generated like any
other perishable number here.

Usage: PYTHONPATH=src python3.12 tools/make_architecture_figures.py
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
TAIL = ROOT / "results/architecture_sweep/FAILURE_TAIL.json"
GATE = ROOT / "results/architecture_sweep/GATE_BY_STRATUM.json"
QUANT = ROOT / "results/architecture_sweep/QUANTISATION_BY_STRATUM.json"
SOURCES = (TAIL, GATE, QUANT)
FIGDIR = ROOT / "figures"
PROVENANCE = ROOT / "results/architecture_sweep/ARCHITECTURE_FIGURE_PROVENANCE.json"
README = ROOT / "README.md"
BEGIN = "<!-- BEGIN AUTOGENERATED: architecture figures -->"
END = "<!-- END AUTOGENERATED: architecture figures -->"

ORANGE = "#d95f02"
BLUE = "#1f78b4"
GREY = "#888888"


def _sha(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def fig_failure_tail(tail: dict) -> tuple[Path, str]:
    st = tail["stratified_by_positive_count"]
    labels = [f"{s['n_cryptic_from']}\u2013{s['n_cryptic_below'] - 1}"
              for s in st]
    means = [s["mean_auc"] for s in st]
    meds = [s["median_auc"] for s in st]
    sds = [s["sd_of_auc"] for s in st]
    nulls = [s["null_sampling_se_at_this_size"] for s in st]
    below = [s["share_below_one_half"] for s in st]
    ns = [s["n_units"] for s in st]

    fig, ax = plt.subplots(1, 2, figsize=(11.0, 4.2))
    x = np.arange(len(st))

    ax[0].errorbar(x, means, yerr=sds, fmt="o", color=ORANGE, capsize=4,
                   markersize=7, linewidth=1.6, label="mean \u00b1 1 sd")
    ax[0].plot(x, meds, "s", color=BLUE, markersize=6, label="median")
    ax[0].errorbar(x, means, yerr=nulls, fmt="none", ecolor=GREY,
                   capsize=8, linewidth=2.4,
                   label="null sampling se at this size")
    ax[0].axhline(0.5, color="k", linewidth=0.8, linestyle=":")
    ax[0].set_xticks(x)
    ax[0].set_xticklabels([f"{a}\nn={b}" for a, b in zip(labels, ns)])
    ax[0].set_xlabel("cryptic residues in the unit")
    ax[0].set_ylabel("per-unit ROC-AUC")
    ax[0].set_ylim(0.35, 1.0)
    ax[0].legend(loc="lower right", fontsize=8, frameon=False)

    ax[1].bar(x, [100 * b for b in below], color=ORANGE, width=0.6)
    for xi, b in zip(x, below):
        ax[1].text(xi, 100 * b + 0.8, f"{100 * b:.1f}%", ha="center",
                   fontsize=9)
    ax[1].set_xticks(x)
    ax[1].set_xticklabels(labels)
    ax[1].set_xlabel("cryptic residues in the unit")
    ax[1].set_ylabel("units scoring below 0.5  (%)")
    ax[1].set_ylim(0, max(100 * b for b in below) * 1.25)
    for a in ax:
        a.spines[["top", "right"]].set_visible(False)
    fig.tight_layout()
    out = FIGDIR / "fig_failure_tail.png"
    fig.savefig(out, dpi=180)
    plt.close(fig)

    p = tail["per_unit_auc"]
    t = tail["tail"]
    cap = (
        f"Where the detector fails, on {p['n']} training units scored on the "
        f"pick half of twelve cluster-disjoint splits. Left, per-unit ROC-AUC "
        f"by the number of cryptic residues the unit contains: mean with one "
        f"standard deviation in orange, median in blue, and in grey the "
        f"sampling standard error a within-unit AUC has at that size under the "
        f"null. The spread is inflated beyond that null at every size and most "
        f"at the smallest, so part of the width is the metric rather than the "
        f"detector; the mean is not, because sampling noise is symmetric and "
        f"the mean falls from "
        f"{st[-1]['mean_auc']:.4f} to {st[0]['mean_auc']:.4f} across the "
        f"strata. Right, the share of units in each stratum scoring below one "
        f"half, which is worse than a coin toss on their own residues: "
        f"{t['n_units_below_one_half']} units do, and they are the population a "
        f"threshold metric is destroyed by. Every architecture sweep in this "
        f"repository was scored by a mean over units, which is "
        f"{p['mean']:.4f} here against a median of {p['median']:.4f}.")
    return out, cap


def fig_gate_by_stratum(gate: dict) -> tuple[Path, str]:
    arms = gate["arms"]
    dep_r = gate["arms"]["r=18 w=1"]["radius"]
    strat = [f"{b['n_cryptic_from']}\u2013{b['n_cryptic_below'] - 1}"
             for b in arms["r=18 w=1"]["by_stratum"]]

    fig, ax = plt.subplots(1, 2, figsize=(11.0, 4.2))
    for i, sn in enumerate(strat):
        rs, vs = [], []
        for k, v in arms.items():
            if v["weight"] != 1.0 or v["radius"] == 0.0:
                continue
            rs.append(v["radius"])
            vs.append(v["by_stratum"][i]["mean_auc"])
        o = np.argsort(rs)
        ax[0].plot(np.asarray(rs)[o], np.asarray(vs)[o], "o-", markersize=5,
                   linewidth=1.5, label=f"{sn} cryptic")
    ax[0].axvline(dep_r, color=GREY, linestyle="--", linewidth=1.2)
    ax[0].text(dep_r + 0.4, ax[0].get_ylim()[0] + 0.01, "deployed",
               color=GREY, fontsize=8, rotation=90, va="bottom")
    ax[0].set_xlabel("gate radius (\u00c5), weight 1.0")
    ax[0].set_ylabel("per-unit ROC-AUC")
    ax[0].legend(fontsize=8, frameon=False)

    pv = gate["paired_against_the_deployed_gate"]["r=14 w=1"]
    keys = ["pooled"] + [s.replace("\u2013", "-") for s in strat]
    ys = np.arange(len(keys))[::-1]
    for yi, k in zip(ys, keys):
        v = pv[k]
        ax[1].plot([v["ci95"][0], v["ci95"][1]], [yi, yi], color=BLUE,
                   linewidth=2.0)
        ax[1].plot([v["mean"]], [yi], "o", color=BLUE, markersize=6)
        ax[1].text(0.0055, yi, f"{v['n_units_better']}/{v['n_units']}",
                   fontsize=8, va="center", color=GREY)
    ax[1].axvline(0.0, color="k", linewidth=0.9)
    ax[1].set_yticks(ys)
    ax[1].set_yticklabels(keys)
    ax[1].set_xlabel("paired ROC-AUC, r=14 minus the deployed r=18")
    ax[1].set_xlim(-0.006, 0.009)
    for a in ax:
        a.spines[["top", "right"]].set_visible(False)
    fig.tight_layout()
    out = FIGDIR / "fig_gate_by_stratum.png"
    fig.savefig(out, dpi=180)
    plt.close(fig)

    sc = gate["selection_check"]
    pooled = pv["pooled"]
    cap = (
        f"The spatial gate swept per pocket size on the training fold, thirteen "
        f"arms sharing one compile per split. Left, per-unit ROC-AUC against "
        f"gate radius at weight 1.0, one line per stratum; the deployed radius "
        f"is marked and is the best for no stratum. Right, the paired "
        f"difference between r=14 and the deployed r=18 on the same units, with "
        f"95% intervals and the count of units improved: "
        f"{pooled['mean']:+.5f} pooled, interval "
        f"[{pooled['ci95'][0]:+.5f}, {pooled['ci95'][1]:+.5f}], "
        f"{pooled['n_units_better']} of {pooled['n_units']} units better, and "
        f"the same size in every stratum rather than concentrated in the small "
        f"pockets the sweep was launched to investigate. Choosing the arm on "
        f"six splits and scoring it on the other six selects the same arm both "
        f"ways round and gives margins of "
        f"{sc['chose_on_splits_0_scored_on_1']['margin_where_it_was_not']:+.5f} "
        f"and "
        f"{sc['chose_on_splits_1_scored_on_0']['margin_where_it_was_not']:+.5f}, "
        f"so the choice replicates and the size is uncertain within that range. "
        f"Nothing is changed on the strength of this: the constant is still "
        f"r=18 and moving it would spend the external confirmation.")
    return out, cap


def render_readme(drawn: list[tuple[Path, str]]) -> None:
    body = [BEGIN, ""]
    for i, (p, cap) in enumerate(drawn, start=1):
        body.append(f"![Architecture figure {i}](figures/{p.name})")
        body.append("")
        body.append(f"**Architecture figure {i}.** {cap}")
        body.append("")
    body.append(END)
    text = README.read_text()
    block = "\n".join(body)
    if BEGIN in text and END in text:
        a = text.index(BEGIN)
        b = text.index(END) + len(END)
        text = text[:a] + block + text[b:]
    else:
        marker = "## Repository layout"
        if marker not in text:
            raise SystemExit("cannot place the architecture figure block: "
                             "neither the markers nor the layout heading found")
        text = text.replace(marker, block + "\n\n" + marker, 1)
    README.write_text(text)


def main() -> int:
    missing = [str(p.relative_to(ROOT)) for p in SOURCES if not p.exists()]
    if missing:
        raise SystemExit(f"missing source artifacts: {missing}")
    FIGDIR.mkdir(exist_ok=True)
    tail = json.loads(TAIL.read_text())
    gate = json.loads(GATE.read_text())
    for name, doc in (("FAILURE_TAIL", tail), ("GATE_BY_STRATUM", gate)):
        if doc.get("reads_test_fold") is not False:
            raise SystemExit(
                f"{name} does not declare reads_test_fold false; this "
                f"generator draws training-fold figures only")

    drawn = [fig_failure_tail(tail), fig_gate_by_stratum(gate)]
    render_readme(drawn)
    PROVENANCE.write_text(json.dumps({
        "schema": "geoaudit.architecture_figure_provenance.v1",
        "clinical_grade": False,
        "reads_test_fold": False,
        "purpose": "training-fold architecture figures, drawn from the frozen "
                   "sweep artifacts so a number in a figure cannot disagree "
                   "with a number in a sentence",
        "generator": "tools/make_architecture_figures.py",
        "why_separate_from_the_official_fold_generator": (
            "that generator draws the official-fold comparison and says so in "
            "its first line. These are cluster-disjoint halves of the training "
            "fold, and one file drawing from two populations is how a figure "
            "ends up read against the wrong denominator"),
        "sources": {str(p.relative_to(ROOT)): _sha(p)
                    for p in SOURCES if p.exists()},
        "figures": {p.name: {"sha256": _sha(p), "bytes": p.stat().st_size,
                             "caption": c} for p, c in drawn},
    }, indent=1) + "\n")
    for p, _c in drawn:
        print(f"wrote {p.relative_to(ROOT)}  {p.stat().st_size} bytes")
    print(f"wrote {PROVENANCE.relative_to(ROOT)}")
    print(f"README block updated between the markers")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
