#!/usr/bin/env python3
"""Draw the training-fold architecture findings, and nothing from the test fold.

Why this is a separate generator
--------------------------------
``make_official_figures.py`` says in its first line that it draws the
official-fold comparison and nothing else, and that sentence is there because a
figure drawn from the wrong population sat in this repository for weeks being
read faster than the text that would have corrected it. These figures are drawn
from cluster-disjoint halves of the **training** fold. Putting them in that
generator would make one file that draws from two populations, and the next
person to add a panel would have to work out which they were in.

What is drawn, and why these two
--------------------------------
Figure A1, per-unit ROC-AUC against the number of cryptic residues in the unit.
Eight readout parameters and five wire families were swept in this repository
and every one of them was scored by a mean over units. That summary hides what
this panel shows at a glance: the deployed field scores 0.5991 on the 188 units
with fewer than ten cryptic residues and 0.8766 on the 201 with more than
twenty-two, and 87 units score below one half. The strip of points below the
0.5 line is the population that a threshold metric is destroyed by, which is
where the withdrawn F1 and MCC claims went.

Figure A2, the spatial gate swept per stratum, with the deployed radius marked.
It carries two things the text needs. The deployed ``r=18`` is not the best
radius for any stratum, and it is the worst of thirteen arms for the smallest.
And the improvement from ``r=14`` is the same size in every stratum, which is
what rules out the reading this sweep was launched to test -- that the optimum
radius rises with pocket size -- and makes it a better global constant instead.

No image carries a title. The descriptive text is emitted from the same
artifacts the plots are drawn from, into ARCHITECTURE_FIGURE_PROVENANCE.json and
into the README block, so a caption stating a unit count is generated like any
other perishable number here.

Usage: PYTHONPATH=src python3.12 tools/make_architecture_figures.py
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
TAIL = ROOT / "results/architecture_sweep/FAILURE_TAIL.json"
GATE = ROOT / "results/architecture_sweep/GATE_BY_STRATUM.json"
QUANT = ROOT / "results/architecture_sweep/QUANTISATION_BY_STRATUM.json"
RECOVERED = ROOT / "results/architecture_sweep/RECOVERED_UNITS_TRAIN.json"
PLMNN = ROOT / "results/official_fold/PLMNN_READ.json"
FAMILIES = {
    "backbone 132": "BACKBONE_WIDE_LIFT",
    "backbone 132 permuted": "BACKBONE_WIDE_PERMUTED_LIFT",
    "sidechain 261": "SIDECHAIN_WIDE_LIFT",
    "sidechain 261 permuted": "SIDECHAIN_PERMUTED_LIFT",
    "void 135": "VOID_LIFT",
    "void 135 permuted": "VOID_PERMUTED_LIFT",
    "conformation 393": "CONFORMATION_LIFT",
    "geometry 528": "GEOMETRY_LIFT",
}
FAMILY_PATHS = {k: ROOT / f"results/architecture_sweep/{v}.json"
                for k, v in FAMILIES.items()}
SOURCES = (TAIL, GATE, QUANT, RECOVERED) + tuple(FAMILY_PATHS.values())
FIGDIR = ROOT / "figures"
PROVENANCE = ROOT / "results/architecture_sweep/ARCHITECTURE_FIGURE_PROVENANCE.json"
README = ROOT / "README.md"
BEGIN = "<!-- BEGIN AUTOGENERATED: architecture figures -->"
END = "<!-- END AUTOGENERATED: architecture figures -->"
CASE_BEGIN = "<!-- BEGIN AUTOGENERATED: four recoveries figure -->"
CASE_END = "<!-- END AUTOGENERATED: four recoveries figure -->"

ORANGE = "#d95f02"
BLUE = "#1f78b4"
GREY = "#888888"
GREEN = "#1a6b1a"
RED = "#8b1a1a"


def _sha(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def fig_failure_tail(tail: dict) -> tuple[Path, str]:
    st = tail["stratified_by_positive_count"]
    labels = [f"{s['n_cryptic_from']}\u2013{s['n_cryptic_below'] - 1}"
              for s in st]
    means = [s["mean_auc"] for s in st]
    meds = [s["median_auc"] for s in st]
    sds = [s["sd_of_auc"] for s in st]
    nulls = [s["null_sampling_se_at_this_size"] for s in st]
    below = [s["share_below_one_half"] for s in st]
    ns = [s["n_units"] for s in st]

    fig, ax = plt.subplots(1, 2, figsize=(11.0, 4.2))
    x = np.arange(len(st))

    ax[0].errorbar(x, means, yerr=sds, fmt="o", color=ORANGE, capsize=4,
                   markersize=7, linewidth=1.6, label="mean \u00b1 1 sd")
    ax[0].plot(x, meds, "s", color=BLUE, markersize=6, label="median")
    ax[0].errorbar(x, means, yerr=nulls, fmt="none", ecolor=GREY,
                   capsize=8, linewidth=2.4,
                   label="null sampling se at this size")
    ax[0].axhline(0.5, color="k", linewidth=0.8, linestyle=":")
    ax[0].set_xticks(x)
    ax[0].set_xticklabels([f"{a}\nn={b}" for a, b in zip(labels, ns)])
    ax[0].set_xlabel("cryptic residues in the unit")
    ax[0].set_ylabel("per-unit ROC-AUC")
    ax[0].set_ylim(0.35, 1.0)
    ax[0].legend(loc="lower right", fontsize=8, frameon=False)

    ax[1].bar(x, [100 * b for b in below], color=ORANGE, width=0.6)
    for xi, b in zip(x, below):
        ax[1].text(xi, 100 * b + 0.8, f"{100 * b:.1f}%", ha="center",
                   fontsize=9)
    ax[1].set_xticks(x)
    ax[1].set_xticklabels(labels)
    ax[1].set_xlabel("cryptic residues in the unit")
    ax[1].set_ylabel("units scoring below 0.5  (%)")
    ax[1].set_ylim(0, max(100 * b for b in below) * 1.25)
    for a in ax:
        a.spines[["top", "right"]].set_visible(False)
    fig.tight_layout()
    out = FIGDIR / "fig_failure_tail.png"
    fig.savefig(out, dpi=180)
    plt.close(fig)

    p = tail["per_unit_auc"]
    t = tail["tail"]
    cap = (
        f"Where the detector fails, on {p['n']} training units scored on the "
        f"pick half of twelve cluster-disjoint splits. Left, per-unit ROC-AUC "
        f"by the number of cryptic residues the unit contains: mean with one "
        f"standard deviation in orange, median in blue, and in grey the "
        f"sampling standard error a within-unit AUC has at that size under the "
        f"null. The spread is inflated beyond that null at every size and most "
        f"at the smallest, so part of the width is the metric rather than the "
        f"detector; the mean is not, because sampling noise is symmetric and "
        f"the mean falls from "
        f"{st[-1]['mean_auc']:.4f} to {st[0]['mean_auc']:.4f} across the "
        f"strata. Right, the share of units in each stratum scoring below one "
        f"half, which is worse than a coin toss on their own residues: "
        f"{t['n_units_below_one_half']} units do, and they are the population a "
        f"threshold metric is destroyed by. Every architecture sweep in this "
        f"repository was scored by a mean over units, which is "
        f"{p['mean']:.4f} here against a median of {p['median']:.4f}.")
    return out, cap


def fig_gate_by_stratum(gate: dict) -> tuple[Path, str]:
    arms = gate["arms"]
    dep_r = gate["arms"]["r=18 w=1"]["radius"]
    strat = [f"{b['n_cryptic_from']}\u2013{b['n_cryptic_below'] - 1}"
             for b in arms["r=18 w=1"]["by_stratum"]]

    fig, ax = plt.subplots(1, 2, figsize=(11.0, 4.2))
    for i, sn in enumerate(strat):
        rs, vs = [], []
        for k, v in arms.items():
            if v["weight"] != 1.0 or v["radius"] == 0.0:
                continue
            rs.append(v["radius"])
            vs.append(v["by_stratum"][i]["mean_auc"])
        o = np.argsort(rs)
        ax[0].plot(np.asarray(rs)[o], np.asarray(vs)[o], "o-", markersize=5,
                   linewidth=1.5, label=f"{sn} cryptic")
    ax[0].axvline(dep_r, color=GREY, linestyle="--", linewidth=1.2)
    ax[0].text(dep_r + 0.4, ax[0].get_ylim()[0] + 0.01, "deployed",
               color=GREY, fontsize=8, rotation=90, va="bottom")
    ax[0].set_xlabel("gate radius (\u00c5), weight 1.0")
    ax[0].set_ylabel("per-unit ROC-AUC")
    ax[0].legend(fontsize=8, frameon=False)

    pv = gate["paired_against_the_deployed_gate"]["r=14 w=1"]
    keys = ["pooled"] + [s.replace("\u2013", "-") for s in strat]
    ys = np.arange(len(keys))[::-1]
    for yi, k in zip(ys, keys):
        v = pv[k]
        ax[1].plot([v["ci95"][0], v["ci95"][1]], [yi, yi], color=BLUE,
                   linewidth=2.0)
        ax[1].plot([v["mean"]], [yi], "o", color=BLUE, markersize=6)
        ax[1].text(0.0055, yi, f"{v['n_units_better']}/{v['n_units']}",
                   fontsize=8, va="center", color=GREY)
    ax[1].axvline(0.0, color="k", linewidth=0.9)
    ax[1].set_yticks(ys)
    ax[1].set_yticklabels(keys)
    ax[1].set_xlabel("paired ROC-AUC, r=14 minus the deployed r=18")
    ax[1].set_xlim(-0.006, 0.009)
    for a in ax:
        a.spines[["top", "right"]].set_visible(False)
    fig.tight_layout()
    out = FIGDIR / "fig_gate_by_stratum.png"
    fig.savefig(out, dpi=180)
    plt.close(fig)

    sc = gate["selection_check"]
    pooled = pv["pooled"]
    cap = (
        f"The spatial gate swept per pocket size on the training fold, thirteen "
        f"arms sharing one compile per split. Left, per-unit ROC-AUC against "
        f"gate radius at weight 1.0, one line per stratum; the deployed radius "
        f"is marked and is the best for no stratum. Right, the paired "
        f"difference between r=14 and the deployed r=18 on the same units, with "
        f"95% intervals and the count of units improved: "
        f"{pooled['mean']:+.5f} pooled, interval "
        f"[{pooled['ci95'][0]:+.5f}, {pooled['ci95'][1]:+.5f}], "
        f"{pooled['n_units_better']} of {pooled['n_units']} units better, and "
        f"the same size in every stratum rather than concentrated in the small "
        f"pockets the sweep was launched to investigate. Choosing the arm on "
        f"six splits and scoring it on the other six selects the same arm both "
        f"ways round and gives margins of "
        f"{sc['chose_on_splits_0_scored_on_1']['margin_where_it_was_not']:+.5f} "
        f"and "
        f"{sc['chose_on_splits_1_scored_on_0']['margin_where_it_was_not']:+.5f}, "
        f"so the choice replicates and the size is uncertain within that range. "
        f"Nothing is changed on the strength of this: the constant is still "
        f"r=18 and moving it would spend the external confirmation.")
    return out, cap


def render_readme(drawn: list[tuple[Path, str]]) -> None:
    body = [BEGIN, ""]
    for i, (p, cap) in enumerate(drawn, start=1):
        body.append(f"![Architecture figure {i}](figures/{p.name})")
        body.append("")
        body.append(f"**Architecture figure {i}.** {cap}")
        body.append("")
    body.append(END)
    text = README.read_text()
    block = "\n".join(body)
    if BEGIN in text and END in text:
        a = text.index(BEGIN)
        b = text.index(END) + len(END)
        text = text[:a] + block + text[b:]
    else:
        marker = "## Repository layout"
        if marker not in text:
            raise SystemExit("cannot place the architecture figure block: "
                             "neither the markers nor the layout heading found")
        text = text.replace(marker, block + "\n\n" + marker, 1)
    README.write_text(text)


def fig_four_recoveries(doc: dict) -> tuple[Path, str]:
    """The four clean cases, the empty mirror, and the P2Rank-only case study.

    Architecture figure 3 already shows every unit as a point. This panel exists
    so a reader who lands on the recovery section sees the count before the
    scatter: four named chains under the strict rule, not a long list, with the
    mirror empty beside them and ``4m7p_A`` drawn only against P2Rank.
    """
    found = float(doc["rule"]["found_at_or_above"])
    missed = float(doc["rule"]["missed_at_or_below"])
    # README table order, strongest margin first; reverse so that unit sits at
    # the top of a horizontal bar chart (matplotlib draws y=0 at the bottom).
    by_unit = {r["unit"]: r for r in doc["recovered"]}
    table_order = ("2xur_B", "8bdi_I", "5f3k_B", "8c3u_A")
    rows = [by_unit[u] for u in table_order if u in by_unit]
    for r in doc["recovered"]:
        if r["unit"] not in {x["unit"] for x in rows}:
            rows.append(r)
    rows = list(reversed(rows))
    caveat = list(doc.get("recovered_but_the_file_is_parsed_differently") or [])
    n_units = int(doc["n_units_compared"])
    n_rec = int(doc["n_recovered"])
    n_mir = int(doc["n_mirror"])

    fig = plt.figure(figsize=(11.8, 5.6))
    gs = fig.add_gridspec(
        1, 2, width_ratios=[1.55, 1.0], wspace=0.32,
        left=0.14, right=0.98, top=0.90, bottom=0.12)
    ax = fig.add_subplot(gs[0, 0])
    axr = fig.add_subplot(gs[0, 1])

    y = np.arange(len(rows))
    h = 0.22
    ours_c, p2_c, pm_c = GREEN, BLUE, ORANGE
    for i, r in enumerate(rows):
        ax.barh(i + h, r["ours"], height=h * 0.9, color=ours_c, zorder=3)
        ax.barh(i, r["p2rank"], height=h * 0.9, color=p2_c, zorder=3)
        ax.barh(i - h, r["pocketminer"], height=h * 0.9, color=pm_c, zorder=3)
        for dy, val, col in (
            (h, r["ours"], ours_c),
            (0.0, r["p2rank"], p2_c),
            (-h, r["pocketminer"], pm_c),
        ):
            ax.text(val + 0.012, i + dy, f"{val:.3f}", va="center",
                    fontsize=8.0, color=col)
        ax.text(-0.02, i, f"{r['unit']}\n{r['n_residues']} res, "
                          f"{r['n_cryptic']} cryptic",
                transform=ax.get_yaxis_transform(), ha="right", va="center",
                fontsize=8.6)

    ax.axvline(found, color=ours_c, lw=1.1, ls="--", zorder=2)
    ax.axvline(missed, color=RED, lw=1.1, ls="--", zorder=2)
    ax.axvline(0.5, color="#bbbbbb", lw=0.8, zorder=1)
    ax.text(found, len(rows) - 0.35 + 0.55, f"ours ≥ {found:.2f}",
            color=ours_c, fontsize=8.2, ha="center", va="bottom")
    ax.text(missed, len(rows) - 0.35 + 0.55, f"baselines ≤ {missed:.2f}",
            color=RED, fontsize=8.2, ha="center", va="bottom")
    ax.set_yticks([])
    ax.set_xlim(0.0, 1.05)
    ax.set_ylim(-0.7, len(rows) - 0.3 + 0.55)
    ax.set_xlabel("within-unit ROC-AUC", fontsize=9.5)
    ax.text(0.0, 1.02,
            f"{n_rec} clean cases of {n_units} training units — not hundreds",
            transform=ax.transAxes, fontsize=10.0, ha="left", va="bottom")
    ax.grid(axis="x", alpha=0.25, lw=0.5)
    ax.set_axisbelow(True)
    ax.legend(
        handles=[
            plt.Rectangle((0, 0), 1, 1, color=ours_c, label="counting field"),
            plt.Rectangle((0, 0), 1, 1, color=p2_c, label="P2Rank"),
            plt.Rectangle((0, 0), 1, 1, color=pm_c, label="PocketMiner"),
        ],
        loc="lower right", fontsize=8.2, frameon=False, ncol=1)

    # Right: mirror empty + 4m7p vs P2Rank only.
    axr.set_xlim(0, 1)
    axr.set_ylim(0, 1)
    axr.axis("off")
    axr.text(0.0, 0.96, "Mirror under the same rule",
             fontsize=10.0, fontweight="bold", va="top")
    axr.text(0.0, 0.88,
             f"both baselines ≥ {found:.2f} and counting field ≤ {missed:.2f}",
             fontsize=8.4, color="#444444", va="top")
    axr.add_patch(plt.Rectangle((0.0, 0.58), 1.0, 0.22, facecolor="#f2c9c9",
                                edgecolor=RED, lw=1.2, transform=axr.transAxes,
                                clip_on=False))
    axr.text(0.5, 0.69, f"{n_mir} units",
             transform=axr.transAxes, ha="center", va="center",
             fontsize=22, fontweight="bold", color=RED)
    axr.text(0.5, 0.61, "the reverse disagreement is empty",
             transform=axr.transAxes, ha="center", va="center",
             fontsize=8.6, color=RED)

    axr.text(0.0, 0.48, "Case study vs P2Rank only — not one of the four",
             fontsize=10.0, fontweight="bold", va="top")
    if caveat:
        r = caveat[0]
        axr.text(0.0, 0.40,
                 f"{r['unit']}  ·  {r['n_residues']} residues, "
                 f"{r['n_cryptic']} cryptic  ·  ensemble deposit",
                 fontsize=8.4, color="#444444", va="top")
        # Two bars against a common axis drawn in data coords via inset.
        inset = axr.inset_axes([0.0, 0.08, 1.0, 0.26])
        labels = ["counting field", "P2Rank"]
        vals = [r["ours"], r["p2rank"]]
        cols = [ours_c, p2_c]
        inset.barh([1, 0], vals, color=cols, height=0.55, zorder=3)
        for yi, val, col in zip([1, 0], vals, cols):
            inset.text(val + 0.015, yi, f"{val:.3f}", va="center",
                       fontsize=9.0, color=col)
        inset.axvline(found, color=ours_c, lw=1.0, ls="--")
        inset.axvline(missed, color=RED, lw=1.0, ls="--")
        inset.axvline(0.5, color="#bbbbbb", lw=0.8)
        inset.set_yticks([1, 0])
        inset.set_yticklabels(labels, fontsize=8.4)
        inset.set_xlim(0, 1.05)
        inset.set_xlabel("within-unit ROC-AUC", fontsize=8.4)
        inset.grid(axis="x", alpha=0.25, lw=0.5)
        inset.set_axisbelow(True)
        axr.text(0.0, 0.02,
                 "same 390-residue universe as P2Rank; excluded from the joint "
                 "table because not every baseline parses the ensemble alike",
                 fontsize=7.8, color="#555555", va="bottom", wrap=True)

    out = FIGDIR / "fig_four_recoveries.png"
    fig.savefig(out, dpi=200)
    plt.close(fig)

    caveat_bit = ""
    if caveat:
        r = caveat[0]
        caveat_bit = (
            f" Right: the mirror under the same rule is empty ({n_mir} units), "
            f"and {r['unit']} is shown only against P2Rank — "
            f"{r['ours']:.3f} vs {r['p2rank']:.3f} on the same "
            f"{r['n_residues']} residues — as a training-fold case study, not "
            f"one of the four."
        )
    cap = (
        f"Four clean recoveries on the training fold, not hundreds. Left: the "
        f"{n_rec} units where the counting field scores within-unit ROC-AUC "
        f"≥ {found:.2f} while both P2Rank and PocketMiner sit ≤ {missed:.2f} "
        f"(chance 0.50), out of {n_units} units where all three methods are "
        f"defined. Each unit shows all three scores; the dashed lines are the "
        f"two cuts fixed before the counts were read."
        f"{caveat_bit} Exploratory, training fold only; pLM-NN is absent; "
        f"clinical_grade is false."
    )
    return out, cap


def render_case_figure(drawn: tuple[Path, str]) -> None:
    p, cap = drawn
    block = "\n".join([
        CASE_BEGIN, "",
        f"![Four recoveries](figures/{p.name})", "",
        f"**Four recoveries.** {cap}", "",
        CASE_END,
    ])
    text = README.read_text()
    if CASE_BEGIN in text and CASE_END in text:
        a = text.index(CASE_BEGIN)
        b = text.index(CASE_END) + len(CASE_END)
        text = text[:a] + block + text[b:]
    else:
        marker = "### Units both published baselines rank at chance"
        if marker not in text:
            raise SystemExit("cannot place the four-recoveries figure: "
                             "section heading missing from README")
        # Sit the figure immediately under the heading, before the prose table.
        text = text.replace(marker, marker + "\n\n" + block, 1)
    README.write_text(text)


def fig_recovered_units(doc: dict) -> tuple[Path, str]:
    """Where the three methods disagree, in both directions at once.

    The left panel is every training unit as one point: our within-unit ROC-AUC
    against the better of the two baselines on that same unit. The two shaded
    corners are the rule -- the upper left is a unit we rank well and both
    baselines rank at chance, the lower right is the mirror. Drawing both corners
    is the point of the figure. A version showing only the corner in our favour
    would be a selection presented as a result, and the reader could not see that
    the mirror is empty at this setting, which is the actual finding.

    The right panel is the threshold ladder, because one row of it is a choice
    and the whole ladder is a measurement.
    """
    import numpy as np

    per = doc["per_unit"]
    ours = np.array([r["ours"] for r in per])
    best = np.array([max(r["p2rank"], r["pocketminer"]) for r in per])
    found = doc["rule"]["found_at_or_above"]
    missed = doc["rule"]["missed_at_or_below"]
    named = {r["unit"] for r in doc["recovered"]}
    caveat = {r["unit"] for r in doc.get(
        "recovered_but_the_file_is_parsed_differently", [])}

    fig, (ax, axl) = plt.subplots(
        1, 2, figsize=(12.2, 4.6), gridspec_kw={"width_ratios": [1.25, 1.0]})

    ax.axhspan(found, 1.0, xmin=0.0, xmax=(missed - 0.2) / 0.8,
               color="#c6e2c6", alpha=0.55, lw=0)
    ax.axvspan(found, 1.0, ymin=0.0, ymax=(missed - 0.2) / 0.8,
               color="#f2c9c9", alpha=0.55, lw=0)
    ax.plot([0.2, 1.0], [0.2, 1.0], color="#999999", lw=0.9, ls="--")
    ax.axhline(0.5, color="#bbbbbb", lw=0.7)
    ax.axvline(0.5, color="#bbbbbb", lw=0.7)

    plain = np.array([r["unit"] not in named and r["unit"] not in caveat
                      for r in per])
    ax.plot(best[plain], ours[plain], "o", ms=3.0, color="#7fb1d3",
            alpha=0.55, mew=0)
    # Offsets alternate so that two units a hundredth apart in ROC-AUC do not
    # print their labels on top of each other; 8c3u_A and 5f3k_B did.
    offsets = ((10, 4), (10, -10), (-12, 9), (-12, -12), (10, 10), (10, -16))
    for k, r in enumerate(doc["recovered"]):
        x, y = max(r["p2rank"], r["pocketminer"]), r["ours"]
        dx, dy = offsets[k % len(offsets)]
        ax.plot(x, y, "o", ms=7, color="#1a6b1a", zorder=3)
        ax.annotate(f"{r['unit']}  ({r['n_cryptic']} cryptic)", (x, y),
                    textcoords="offset points", xytext=(dx, dy), fontsize=8.4,
                    ha="left" if dx > 0 else "right")
    for r in doc.get("recovered_but_the_file_is_parsed_differently", []):
        x, y = max(r["p2rank"], r["pocketminer"]), r["ours"]
        ax.plot(x, y, "s", ms=7, mfc="none", mec="#1a6b1a", mew=1.4, zorder=3)
        ax.annotate(f"{r['unit']}  parsed differently", (x, y),
                    textcoords="offset points", xytext=(0, 13), fontsize=8.4,
                    ha="center", color="#555555")
    ax.set_xlabel("the better of P2Rank and PocketMiner on that unit, ROC-AUC",
                  fontsize=9.5)
    ax.set_ylabel("counting field, ROC-AUC within the unit", fontsize=9.5)
    ax.set_xlim(0.2, 1.0)
    ax.set_ylim(0.2, 1.0)
    # Below the shaded corner rather than inside it: the corner holds the named
    # points and their labels, and a caption placed there sits on top of them.
    ax.text(0.03, 0.70, f"we rank it, both baselines do not\n"
                        f"{doc['n_recovered']} units",
            transform=ax.transAxes, va="top", fontsize=8.6, color="#1a6b1a")
    ax.text(0.97, 0.03, f"both rank it, we do not\n{doc['n_mirror']} units",
            transform=ax.transAxes, va="bottom", ha="right", fontsize=8.6,
            color="#8b1a1a")
    ax.grid(alpha=0.2, lw=0.5)
    ax.set_axisbelow(True)

    lad = doc["threshold_ladder"]
    y = np.arange(len(lad))[::-1]
    axl.barh(y + 0.19, [r["n_recovered"] for r in lad], height=0.36,
             color="#1a6b1a", label="we rank it, both baselines do not")
    axl.barh(y - 0.19, [r["n_mirror"] for r in lad], height=0.36,
             color="#8b1a1a", label="both rank it, we do not")
    axl.set_yticks(y)
    axl.set_yticklabels([f"{r['found_at_or_above']:.2f} / "
                         f"{r['missed_at_or_below']:.2f}" for r in lad],
                        fontsize=8.6)
    axl.set_xlabel(f"units, of {doc['n_units_compared']}", fontsize=9.5)
    axl.set_ylabel("found \u2265  /  missed \u2264", fontsize=9.5)
    axl.set_xlim(0, max(r["n_recovered"] for r in lad) * 1.45)
    axl.legend(fontsize=8.3, loc="upper right", frameon=False)
    axl.grid(axis="x", alpha=0.2, lw=0.5)
    axl.set_axisbelow(True)

    fig.tight_layout()
    out = FIGDIR / "fig_recovered_units.png"
    fig.savefig(out, dpi=200)
    plt.close(fig)

    strict = lad[0]
    caption = (
        f"Training-fold disagreements between the counting field and the two "
        f"published baselines it can be compared against there, in both "
        f"directions. Left: every one of the {doc['n_units_compared']} units as "
        f"one point, our within-unit ROC-AUC against the better of P2Rank and "
        f"PocketMiner on that same unit. The green corner is the rule fixed "
        f"before the counts were read \u2014 ours \u2265 {strict['found_at_or_above']:.2f} "
        f"with both baselines \u2264 {strict['missed_at_or_below']:.2f}, chance "
        f"being 0.50 \u2014 and the red corner is its mirror, which holds "
        f"{doc['n_mirror']} units. {doc['n_recovered']} units are named; "
        f"4m7p_A is drawn hollow and not counted in that joint rule because its "
        f"deposit is a twenty-conformer ensemble and not every baseline parses "
        f"it alike — against P2Rank alone both score the same 390 residues "
        f"(0.918 vs 0.439), reported separately as a training-fold case study. "
        f"Right: the same two counts at eight strictness settings, reported "
        f"whole because one row of a ladder is a choice. pLM-NN is absent and "
        f"cannot be added here: its published head was fitted on these very "
        f"chains, where it scores 0.96 against 0.82 on the official fold, and a "
        f"rule asking whether a baseline sits at chance cannot be applied to a "
        f"baseline that has memorised the unit. So this compares against two "
        f"baselines and not three, and the three-baseline version of the "
        f"question was answered on the official fold under a preregistered "
        f"plan, where it returned 0 recoveries against 1 mirror. Exploratory, "
        f"training fold only, no test-fold read.")
    return out, caption


def fig_family_ladder(fams: dict, plm: dict) -> tuple[Path, str]:
    """Five families, both of their control arms, and the gap they are aimed at.

    Left: the lift each family buys over the deployed detector, with its 95 %
    interval, and beside each bar the two arms that exist to destroy it --- a
    control spending the same table budget on wires already deployed, and a
    permutation preserving every column's marginal while destroying which
    residue a row describes. Drawing the arms on the same axis as the bar is the
    point. A panel showing only the bars would be five numbers with no way to
    see that the permutations are *negative*, which is the part that says the
    lift belongs to the residue being scored.

    Right: what happens when families are combined, against what would happen if
    they were independent. This repository has read a family's lift the wrong
    way before --- 267 generated descriptors worth +0.0081 against a 35-invariant
    baseline were worth -0.0009 against the detector that ships --- so the
    combined arms are measured rather than summed, and the shortfall between the
    measured bar and the dashed marker is the part that was being counted twice.

    The vertical rule on the left is the deficit all of this is aimed at. It is
    drawn because the alternative is a panel of encouraging bars with no scale:
    the largest of them is under two fifths of the gap, and a reader should see
    that without doing arithmetic.
    """
    order = [("backbone 132", "FamBkb"), ("sidechain 261", "FamSide"),
             ("void 135", "FamVoid"), ("conformation 393", "FamConf"),
             ("geometry 528", "FamGeom")]
    fig, (ax, axr) = plt.subplots(
        1, 2, figsize=(12.6, 4.8), gridspec_kw={"width_ratios": [1.55, 1.0]})

    y = np.arange(len(order))[::-1]
    for k, (name, _stem) in enumerate(order):
        d = fams[name]
        u = d["minus_narrow"]["union"]
        lo, hi = u["ci95"]
        ax.barh(y[k], u["mean"], height=0.5, color=BLUE, zorder=2)
        ax.plot([lo, hi], [y[k]] * 2, color="#0d3d57", lw=1.6, zorder=3)
        ctrl = d["minus_narrow"].get("more_old")
        if ctrl:
            ax.plot(ctrl["mean"], y[k], "o", ms=6, mfc="white", mec=GREY,
                    mew=1.5, zorder=4)
        perm = fams.get(name + " permuted")
        if perm:
            ax.plot(perm["minus_narrow"]["union"]["mean"], y[k], "D", ms=5.5,
                    color=RED, zorder=4)
        ax.text(u["mean"] + 0.00035, y[k] + 0.20,
                f"{u['mean']:+.5f}  {u['n_splits_positive']}/{u['n_splits']}",
                fontsize=8.4, va="center")

    deficit = abs(plm["primary_comparison"]["mean"])
    ax.axvline(deficit, color=ORANGE, lw=1.6, ls="--", zorder=5)
    # Rotated onto the rule itself. Laid horizontally at the top it sat over the
    # first bar's annotation, and the two numbers a reader most needs to compare
    # were the two that overlapped.
    ax.text(deficit - 0.0006, len(order) / 2 - 0.5,
            f"pLM-NN leads by {deficit:.4f} on the official fold",
            fontsize=8.6, color=ORANGE, ha="center", va="center", rotation=90)
    ax.axvline(0, color="#444444", lw=0.9)
    ax.set_yticks(y)
    ax.set_yticklabels([n for n, _ in order], fontsize=9.2)
    ax.set_xlabel("mean per-unit ROC-AUC over the deployed detector, "
                  "12 cluster-disjoint halvings", fontsize=9.5)
    ax.set_xlim(-0.006, deficit * 1.16)
    ax.grid(axis="x", alpha=0.2, lw=0.5)
    ax.set_axisbelow(True)
    handles = [
        plt.Line2D([], [], marker="s", ls="", color=BLUE, ms=8,
                   label="family, with 95 % interval"),
        plt.Line2D([], [], marker="o", ls="", mfc="white", mec=GREY, mew=1.5,
                   ms=7, label="control: same tables, deployed wires only"),
        plt.Line2D([], [], marker="D", ls="", color=RED, ms=6,
                   label="rows permuted within each chain"),
    ]
    # Anchored past where the bar annotations end, in the band between the
    # longest label and the deficit rule. "Upper right" clipped the first bar's
    # count and "lower right" sat on the last bar's; this is the gap between.
    ax.legend(handles=handles, fontsize=8.2, loc="upper left", frameon=False,
              bbox_to_anchor=(0.60, 1.0))

    pairs = [("conformation 393", ("backbone 132", "sidechain 261")),
             ("geometry 528", ("backbone 132", "sidechain 261", "void 135"))]
    yy = np.arange(len(pairs))[::-1]
    for k, (combo, parts) in enumerate(pairs):
        got = fams[combo]["minus_narrow"]["union"]["mean"]
        want = sum(fams[p]["minus_narrow"]["union"]["mean"] for p in parts)
        axr.barh(yy[k], got, height=0.42, color=GREEN, zorder=2)
        axr.plot([want] * 2, [yy[k] - 0.30, yy[k] + 0.30], color="#444444",
                 lw=1.8, ls="--", zorder=4)
        axr.text(want + 0.00055, yy[k], f"{got / want:.0%} of the sum",
                 fontsize=8.6, va="center")
    axr.set_yticks(yy)
    axr.set_yticklabels([f"{c}\n= {' + '.join(p.split()[0] for p in parts)}"
                         for c, parts in pairs], fontsize=8.8)
    axr.set_xlabel("measured lift (bar), sum of parts (dashed)", fontsize=9.5)
    axr.set_xlim(0, max(sum(fams[p]["minus_narrow"]["union"]["mean"]
                            for p in parts) for _c, parts in pairs) * 1.42)
    axr.grid(axis="x", alpha=0.2, lw=0.5)
    axr.set_axisbelow(True)
    # Matplotlib's default put eight ticks on a 0.017-wide axis and they ran
    # together into one string of digits.
    axr.xaxis.set_major_locator(matplotlib.ticker.MaxNLocator(4))
    axr.tick_params(axis="x", labelsize=8.4)

    fig.tight_layout()
    out = FIGDIR / "fig_family_ladder.png"
    fig.savefig(out, dpi=200)
    plt.close(fig)

    g = fams["geometry 528"]["minus_narrow"]["union"]
    v = fams["void 135"]["minus_narrow"]["union"]["mean"]
    c = fams["conformation 393"]["minus_narrow"]["union"]["mean"]
    caption = (
        f"The three wire families that are not null, their two control arms, "
        f"and the two stacks built from them. Left: lift over the deployed "
        f"detector on twelve cluster-disjoint halvings of the training fold, "
        f"with the 95 % interval. Every family's control arm \u2014 the same "
        f"number of added tables, drawn from wires already deployed \u2014 sits "
        f"at zero, so added cells are not the mechanism; every permuted arm, "
        f"which preserves each column's multiset over the chain and destroys "
        f"only which residue a row describes, is *negative*, so columns of "
        f"these shapes attached to the wrong residue are worse than adding "
        f"nothing. Right: each stack against the sum of its parts. backbone and "
        f"side-chain are computed from overlapping atom sets and share about a "
        f"fifth of what they carry; void, which reads the connectivity of the "
        f"empty space rather than the scored residue's own atoms, keeps "
        f"{(g['mean'] - c) / v:.0%} of its standalone value when stacked on "
        f"both. The dashed rule on the left is the gap this is aimed at: the "
        f"largest bar, {g['mean']:+.5f} on {g['n_splits_positive']} of "
        f"{g['n_splits']} splits, is {g['mean'] / deficit:.0%} of the "
        f"official-fold deficit to pLM-NN. Training fold only; nothing here is "
        f"deployed and no held-out set was read.")
    return out, caption


def main() -> int:
    missing = [str(p.relative_to(ROOT)) for p in SOURCES if not p.exists()]
    if missing:
        raise SystemExit(f"missing source artifacts: {missing}")
    FIGDIR.mkdir(exist_ok=True)
    tail = json.loads(TAIL.read_text())
    gate = json.loads(GATE.read_text())
    rec = json.loads(RECOVERED.read_text())
    for name, doc in (("FAILURE_TAIL", tail), ("GATE_BY_STRATUM", gate),
                      ("RECOVERED_UNITS_TRAIN", rec)):
        if doc.get("reads_test_fold") is not False:
            raise SystemExit(
                f"{name} does not declare reads_test_fold false; this "
                f"generator draws training-fold figures only")

    fams = {k: json.loads(p.read_text()) for k, p in FAMILY_PATHS.items()}
    for k, d in fams.items():
        if d.get("reads_test_fold") is not False:
            raise SystemExit(f"{k} does not declare reads_test_fold false")
    # The one number in this generator that comes off the held-out fold is the
    # deficit the families are aimed at, and it is read from an artifact that is
    # already in the ledger rather than recomputed. Drawing it costs no new read
    # and omitting it would leave a panel of bars with no scale.
    plm = json.loads(PLMNN.read_text())

    drawn = [fig_failure_tail(tail), fig_gate_by_stratum(gate),
             fig_family_ladder(fams, plm), fig_recovered_units(rec)]
    case = fig_four_recoveries(rec)
    render_readme(drawn)
    render_case_figure(case)
    all_figs = drawn + [case]
    PROVENANCE.write_text(json.dumps({
        "schema": "geoaudit.architecture_figure_provenance.v1",
        "clinical_grade": False,
        "reads_test_fold": False,
        "purpose": "training-fold architecture figures, drawn from the frozen "
                   "sweep artifacts so a number in a figure cannot disagree "
                   "with a number in a sentence",
        "generator": "tools/make_architecture_figures.py",
        "why_separate_from_the_official_fold_generator": (
            "that generator draws the official-fold comparison and says so in "
            "its first line. These are cluster-disjoint halves of the training "
            "fold, and one file drawing from two populations is how a figure "
            "ends up read against the wrong denominator"),
        "sources": {str(p.relative_to(ROOT)): _sha(p)
                    for p in SOURCES + (PLMNN,) if p.exists()},
        "the_one_held_out_number_drawn": {
            "what": "the pLM-NN deficit marked on the family-ladder panel",
            "from": "results/official_fold/PLMNN_READ.json",
            "why_this_is_not_a_new_read": (
                "the number is already in the test-fold ledger under read "
                "index 10 and is quoted, not recomputed. A panel of lifts with "
                "no scale invites the reader to supply their own"),
        },
        "figures": {p.name: {"sha256": _sha(p), "bytes": p.stat().st_size,
                             "caption": c} for p, c in all_figs},
    }, indent=1) + "\n")
    for p, _c in all_figs:
        print(f"wrote {p.relative_to(ROOT)}  {p.stat().st_size} bytes")
    print(f"wrote {PROVENANCE.relative_to(ROOT)}")
    print(f"README block updated between the markers")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
