#!/usr/bin/env python3
"""Draw the official-fold comparison from the frozen artifacts, and nothing else.

The repository already carried a file called fig_baseline_comparison.png. It
plotted the 14-structure ESR1 pilot, on a split its own summary records as not
cluster-disjoint, with method labels ("geometric manifold prior", "exact-form
filter") that appear nowhere in the manuscript, showing every one of our
detectors at zero. A reader opening the repository saw that image and formed a
picture unrelated to the result. A wrong figure is worse than no figure, because
it is read faster than the text that would correct it.

These two are generated from the same frozen JSON the paper's macros read, so a
number in a figure cannot disagree with a number in a sentence.

Figure 1, the four metrics side by side with bootstrap intervals. Ordered by
ROC-AUC, P2Rank marked, so the eye gets the comparison the benchmark exists for
before it reaches the caption.

Figure 2, the paired differences against P2Rank as a forest plot, one row per
metric, with the interval and the shared-structure count. This is the honest
figure: three intervals straddle zero and the drawing says so at a glance, where
a bar chart of point estimates would quietly imply an ordering the fold cannot
support. The ROC-AUC row also carries the standard error of a fold mean, because
a margin has to be read against the scale of the measurement rather than against
zero.

No image here carries a title. Two of them used to: a two-line suptitle on the
first, a title and a subtitle band on the second. In a manuscript that text is the
caption, it belongs under the figure, and burning it into the pixels means it
cannot be typeset, cannot be translated, and cannot be corrected without
redrawing. So the descriptive text is emitted here instead, from the same frozen
artifacts the plots are drawn from, into FIGURE_PROVENANCE.json and into the
README block below each image. A caption stating a seed and a structure count is
as perishable as any other number in this repository and is generated like one.

Usage: PYTHONPATH=src python3.12 tools/make_official_figures.py
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
BOOT = ROOT / "results/official_fold/OFFICIAL_MULTI_METHOD_BOOTSTRAP_vs_P2RANK.json"
LEDGER = ROOT / "results/official_fold/TEST_FOLD_ACCESS_LEDGER.json"
TELEMETRY = ROOT / "results/cryptobench_official/TELEMETRY.json"
SEEDS = ROOT / "results/official_fold/SEED_SENSITIVITY.json"
CASES = ROOT / "results/official_fold/CASE_STUDIES.json"
PREREG_READ = ROOT / "results/official_fold/PREREGISTERED_READ.json"
MATCH_READ = ROOT / "results/official_fold/MATCHED_OPERATING_POINT_READ.json"
FULL_READ = ROOT / "results/official_fold/MATCHED_FULL_READ.json"
SUBGROUP_READ = ROOT / "results/official_fold/SUBGROUP_READ.json"
AUDIT = ROOT / "results/official_fold/AUDIT_DECOMPOSITION.json"
CURVE = ROOT / "results/official_fold/THRESHOLD_CURVE.json"
EMDB = ROOT / "results/external/EMDB_MAPS.json"
DIFFICULTY = ROOT / "results/external/EXTERNAL_SET_DIFFICULTY.json"
SETBC_READ = ROOT / "results/external/SETBC_READ.json"
SETBC_DIFF = ROOT / "results/external/SETBC_DIFFICULTY.json"
WHERE_WE = ROOT / "results/external/WHERE_WE_BEAT_PLMNN.json"
RHOA = ROOT / "results/external/RHOA_CASE_STUDY.json"
RESIDUE_REC = ROOT / "results/external/RESIDUE_RECOVERIES_VS_PLMNN.json"
SETN_READ = ROOT / "results/external/SETN_READ.json"
DUAL_REC = ROOT / "results/external/DUAL_BASELINE_RECOVERIES.json"
GEOM_PROBE = ROOT / "results/official_fold/GEOMETRY_FIELD_VS_PLMNN_PROBE.json"
GEOM_LEN = ROOT / "results/official_fold/GEOMETRY_PLM_DELTA_COVARIATES.json"
FIGDIR = ROOT / "figures"
PROVENANCE = ROOT / "results/official_fold/FIGURE_PROVENANCE.json"
README = ROOT / "README.md"
# SETN_READ is absent by design since 2026-08-03: the Set N material moved to the
# private atlas repository. Its drawing site is already guarded on existence, so
# the figure is simply not drawn; §5.4 of the README retains the result.
SOURCES = (BOOT, LEDGER, TELEMETRY, SEEDS, CASES, AUDIT, PREREG_READ, MATCH_READ,
           FULL_READ, SUBGROUP_READ, CURVE, EMDB, DIFFICULTY, SETBC_READ, SETBC_DIFF,
           WHERE_WE, RHOA, RESIDUE_REC, DUAL_REC, GEOM_PROBE, GEOM_LEN)
BEGIN = "<!-- BEGIN AUTOGENERATED: figures -->"
END = "<!-- END AUTOGENERATED: figures -->"

METRICS = [("residue_auc", "ROC-AUC"), ("residue_pr_auc", "PR-AUC"),
           ("residue_mcc", "MCC"), ("residue_f1", "F1")]
LABEL = {
    "table_field": "Table field (ours)",
    "algebraic_field_linear": "Algebraic field, fitted readout",
    "algebraic_field": "Algebraic field",
    "quaternary_lut_seq": "Quaternary LUT + sequence",
    "quaternary_lut": "Quaternary LUT",
    "geometric_foundation": "Rigid geometric",
    "sstar_pocket": "Anisotropic shear",
    "ultrametric_shear_oracle": "Ultrametric shear",
    "fstar_pocket": "Isotropic ablation",
    "random_bbox": "Chance",
    "p2rank": "P2Rank 2.5.1 (baseline)",
}


def _fold_se() -> float:
    rows = json.loads(TELEMETRY.read_text())["rows"]
    v = [r["residue_auc"] for r in rows
         if r["method"] == "table_field" and r.get("residue_auc") is not None]
    mu = sum(v) / len(v)
    var = sum((x - mu) ** 2 for x in v) / (len(v) - 1)
    return (var / len(v)) ** 0.5


def figure_metrics(boot: dict) -> Path:
    order = sorted(
        boot["metrics"]["residue_auc"]["per_method"].items(),
        key=lambda kv: -(kv[1]["point"] or 0))
    names = [m for m, _ in order]

    fig, axes = plt.subplots(1, 4, figsize=(17, 6.2), sharey=True)
    for ax, (key, title) in zip(axes, METRICS):
        pm = boot["metrics"][key]["per_method"]
        ys = list(range(len(names)))[::-1]
        for y, m in zip(ys, names):
            rec = pm.get(m) or {}
            pt = rec.get("point")
            if pt is None:
                # MCC is undefined for a detector that calls nothing positive.
                # Saying so beats an absent bar the reader has to interpret.
                ax.text(0.02, y, "undefined", va="center", fontsize=8,
                        color="#888888", style="italic")
                continue
            lo, hi = rec.get("ci_low"), rec.get("ci_high")
            colour = ("#d94801" if m == "table_field"
                      else "#2c7fb8" if m == "p2rank" else "#bdbdbd")
            ax.barh(y, pt, color=colour, edgecolor="black", linewidth=0.5,
                    height=0.68)
            if lo is not None and hi is not None:
                ax.plot([lo, hi], [y, y], color="black", lw=1.1)
                ax.plot([lo, lo], [y - 0.16, y + 0.16], color="black", lw=1.1)
                ax.plot([hi, hi], [y - 0.16, y + 0.16], color="black", lw=1.1)
            ax.text(pt, y + 0.34, f"{pt:.3f}", fontsize=7.5, ha="center")
        # Below the axes, not above it. A panel identifier is the one piece of
        # text a figure cannot do without, and in a manuscript nothing sits on
        # top of a plot: what the reader needs to interpret it belongs in the
        # caption, and the caption is under the image.
        ax.set_xlabel(title, fontsize=11)
        ax.set_xlim(0, 1.0 if key == "residue_auc" else None)
        ax.grid(axis="x", alpha=0.25, lw=0.5)
        ax.set_axisbelow(True)
    axes[0].set_yticks(list(range(len(names)))[::-1])
    axes[0].set_yticklabels([LABEL.get(m, m) for m in names], fontsize=9)

    fig.tight_layout()
    out = FIGDIR / "fig_official_fold_metrics.png"
    fig.savefig(out, dpi=200)
    plt.close(fig)

    caption = (
        f"Per-residue detection on the official CryptoBench apo test fold "
        f"({boot['n_structures']} single-chain units, MMseqs2 10% "
        f"cluster-disjoint). Bars are means over structures, ordered by "
        f"ROC-AUC; whiskers are 95% bootstrap intervals ({boot['n_boot']:,} "
        f"resamples, seed {boot['seed']}). The table field is drawn in orange "
        f"and P2Rank 2.5.1, the baseline, in blue. MCC is undefined for a "
        f"detector that calls nothing positive; those entries are marked "
        f"rather than left blank.")
    return out, caption


def _seed_survival() -> dict[str, tuple[int, int]]:
    """How many resampling seeds each verdict survives.

    Without this the figure would colour MCC as resolved while the manuscript
    calls it unresolved, because its interval clears zero at the frozen seed and
    at few others. A figure that contradicts the text is read first and believed
    longest, so the drawing reads the same artifact the prose does.
    """
    if not SEEDS.exists():
        return {}
    d = json.loads(SEEDS.read_text())
    n = d.get("n_seeds")
    out = {}
    for block in ("per_metric", "metrics"):
        for k, v in (d.get(block) or {}).items():
            if isinstance(v, dict):
                sig = (v.get("n_excluding_zero")
                       if v.get("n_excluding_zero") is not None
                       else v.get("n_seeds_excluding_zero"))
                if sig is not None and n:
                    out[k] = (int(sig), int(n))
    return out


def figure_paired(boot: dict, led: dict) -> Path:
    se = _fold_se()
    survival = _seed_survival()
    rows = []
    for key, title in METRICS:
        d = (boot["metrics"][key].get("paired_vs_baseline") or {}).get("table_field")
        if d and d.get("delta_point") is not None:
            rows.append((key, title, d))

    # Four rows. The height used to carry a title and a subtitle band as well;
    # without them the same canvas leaves the rows swimming in white space.
    fig, ax = plt.subplots(figsize=(11.5, 3.4))
    ys = list(range(len(rows)))[::-1]
    for y, (key, title, d) in zip(ys, rows):
        lo, hi, pt = d["delta_ci_low"], d["delta_ci_high"], d["delta_point"]
        clears = not d.get("crosses_zero", True)
        sig, n_seeds = survival.get(key, (None, None))
        # Reported as resolved only if the interval clears zero AND the verdict
        # does not depend on which resample happened to be drawn.
        robust = clears and (sig is None or n_seeds is None or sig == n_seeds)
        colour = "#d94801" if robust else "#8c8c8c"
        ax.plot([lo, hi], [y, y], color=colour, lw=2.4, solid_capstyle="butt")
        ax.plot(pt, y, "o", color=colour, ms=7, zorder=3)
        if robust:
            verdict = "resolved"
        elif clears:
            verdict = f"clears zero at {sig}/{n_seeds} seeds \u2014 unresolved"
        else:
            verdict = "contains zero"
        seeds = "" if sig is None else f"   seeds {sig}/{n_seeds}"
        ax.text(hi + 0.004, y,
                f"{pt:+.4f}  [{lo:+.4f}, {hi:+.4f}]   "
                f"n={d['n_paired_structures']}{seeds}   {verdict}",
                va="center", fontsize=8.8,
                color="black" if robust else "#555555")
    ax.axvline(0, color="black", lw=1.0)
    ax.axvspan(-se, se, color="#2c7fb8", alpha=0.10, lw=0)
    ax.set_yticks(ys)
    ax.set_yticklabels([t for _, t, _ in rows], fontsize=10)
    ax.set_xlabel("paired difference, table field minus P2Rank "
                  "(positive favours the table field)", fontsize=10)
    ax.set_xlim(-0.05, 0.19)
    ax.grid(axis="x", alpha=0.25, lw=0.5)
    ax.set_axisbelow(True)
    fig.tight_layout()
    out = FIGDIR / "fig_paired_vs_p2rank.png"
    fig.savefig(out, dpi=200)
    plt.close(fig)

    caption = (
        f"Paired differences against P2Rank, on the structures where both are "
        f"defined: one row per metric, showing the point estimate, the 95% "
        f"bootstrap interval and the number of shared structures. The shaded "
        f"band is \u00b11 standard error of a fold mean ({se:.4f}); "
        f"{led['n_distinct_architectures_evaluated']} of our architectures have "
        f"been scored on this fold, so a margin inside that band is not an "
        f"ordering. A row is called resolved only where the interval clears "
        f"zero and the verdict survives every resampling seed, which is why "
        f"three of the four are not.")
    return out, caption


FUNCTIONALS = [
    ("mean", "mean"),
    ("stratified_by_length", "mean, chain length fixed"),
    ("trimmed10", "10% trimmed mean"),
    ("trimmed20", "20% trimmed mean"),
    ("median", "median"),
]


def figure_functionals(read: dict) -> tuple[Path, str]:
    """Why the fold resolves an ordering under one functional and not another.

    Left, the paired differences themselves, because every number on the right
    is a summary of this one histogram and the reader should see the shape
    before the summaries. The win rate is not plotted beside the others: it
    lives on a probability scale and putting it on an axis of ROC-AUC
    differences would invite exactly the cross-scale comparison the selection
    rule refuses to make. It is already in the left panel, as the mass on the
    positive side of zero.
    """
    import numpy as np

    rows = json.loads(TELEMETRY.read_text())["rows"]
    by = {}
    for r in rows:
        if r["method"] in ("table_field", "p2rank") and r.get("residue_auc"):
            by.setdefault(r["method"], {})[r["unit_id"]] = float(r["residue_auc"])
    shared = sorted(set(by["table_field"]) & set(by["p2rank"]))
    d = np.array([by["table_field"][u] - by["p2rank"][u] for u in shared])
    sh = read["shape_of_the_differences"]
    cand = {c["statistic"]: c for c in read["candidates"]}
    k = sh["n_trimmed_each_side"]
    lo_cut, hi_cut = np.sort(d)[k], np.sort(d)[len(d) - k - 1]

    fig, (axh, axf) = plt.subplots(
        1, 2, figsize=(12.4, 3.9), gridspec_kw={"width_ratios": [1.05, 1.35]})

    axh.hist(d, bins=44, color="#7fb1d3", edgecolor="white", linewidth=0.4)
    axh.axvspan(d.min(), lo_cut, color="#bdbdbd", alpha=0.45, lw=0)
    axh.axvspan(hi_cut, d.max(), color="#bdbdbd", alpha=0.45, lw=0)
    axh.axvline(0, color="black", lw=1.0)
    axh.set_xlabel("per-structure ROC-AUC, table field minus P2Rank",
                   fontsize=9.5)
    axh.set_ylabel("structures", fontsize=9.5)
    axh.text(0.02, 0.95,
             f"{sh['n_baseline_ahead']} behind   |   {sh['n_field_ahead']} ahead\n"
             f"shaded: the {k} + {k} the 20% trim discards\n"
             f"discarded losses {sh['worst_losses_mean']:+.3f}, "
             f"wins {sh['best_wins_mean']:+.3f}",
             transform=axh.transAxes, va="top", fontsize=8.3)
    axh.grid(axis="y", alpha=0.22, lw=0.5)
    axh.set_axisbelow(True)

    # The annotations sit in a fixed column rather than trailing each interval,
    # so that five rows of unequal width stay readable and nothing runs off the
    # canvas as the numbers move.
    text_x = 0.068
    ys = list(range(len(FUNCTIONALS)))[::-1]
    for y, (key, label) in zip(ys, FUNCTIONALS):
        c = cand[key]
        resolved = not c["crosses_zero"]
        colour = "#d94801" if resolved else "#8c8c8c"
        axf.plot([c["ci_low"], c["ci_high"]], [y, y], color=colour, lw=2.4,
                 solid_capstyle="butt")
        axf.plot(c["point"], y, "o", color=colour, ms=7, zorder=3)
        axf.text(text_x, y,
                 f"{c['point']:+.4f}  [{c['ci_low']:+.4f}, {c['ci_high']:+.4f}]"
                 f"   p={c['p_two_sided_bootstrap']:.3f}   "
                 f"{'resolved' if resolved else 'contains zero'}",
                 va="center", fontsize=8.6,
                 color="black" if resolved else "#555555")
    axf.axvline(0, color="black", lw=1.0)
    axf.set_yticks(ys)
    axf.set_yticklabels(
        [f"{lab}\n(fixed in advance)" if cand[k]["preregistered"] else lab
         for k, lab in FUNCTIONALS], fontsize=9.5)
    axf.set_xlabel("the same paired differences, summarised five ways",
                   fontsize=9.5)
    axf.set_xlim(-0.03, 0.20)
    axf.grid(axis="x", alpha=0.22, lw=0.5)
    axf.set_axisbelow(True)

    fig.tight_layout()
    out = FIGDIR / "fig_functional_choice.png"
    fig.savefig(out, dpi=200)
    plt.close(fig)

    pre = read["preregistered_result"]
    mean = read["mean_reported_beside_it"]
    wr = next(c for c in read["candidates"] if c["statistic"] == "win_rate")
    caption = (
        f"One set of {sh['n']} paired differences, and what follows from how it "
        f"is summarised. Left, the differences themselves: the field is ahead on "
        f"{sh['n_field_ahead']} structures and behind on {sh['n_baseline_ahead']}, "
        f"a win rate {wr['point']:+.4f} above one half (p={wr['p_two_sided_bootstrap']:.3f}), "
        f"and the shaded tails are what a 20% trim discards \u2014 losses "
        f"averaging {sh['worst_losses_mean']:+.4f} against wins of "
        f"{sh['best_wins_mean']:+.4f}. That asymmetry is why the mean sits at "
        f"{mean['point']:+.4f} while the middle 60% sits at {pre['point']:+.4f}. "
        f"Right, five location summaries of those same numbers with 95% "
        f"bootstrap intervals. The 20% trimmed mean was chosen on the training "
        f"partition and committed in "
        f"{read['provenance_of_the_choice']['committed_in'][:7]} before this "
        f"fold was read for it; the others are shown because reporting only the "
        f"chosen one would hide whether the choice landed on the flattering "
        f"summary. The mean is unresolved and stays in the paper: it is the "
        f"functional that speaks to the discarded tail, where the field's "
        f"failures are worse than P2Rank's.")
    return out, caption


COV_LABEL = {
    "prmsd": "apo/holo pocket RMSD",
    "n_true": "pocket size (labelled residues)",
    "positive_rate": "positive rate",
    "chain_length": "chain length",
    "mean_bfactor": "mean B-factor of the pocket",
}


def figure_subgroups(sub: dict) -> tuple[Path, str]:
    """Where on the fold the two detectors differ, and why that is not a finding.

    Left, every chain as one bar, sorted. A reader who has been shown only a
    mean and a trimmed mean has no way to tell whether the difference is a small
    shift of the whole fold or a few structures carrying it, and this panel
    answers that before any subgroup is drawn.

    Right, the fifteen bands. The Bonferroni interval is drawn on top of the
    uncorrected one rather than instead of it, because the point of the panel is
    what the correction costs; and the one band that clears it is annotated with
    its own covariate's trend test, which is null, since a band without a
    dose-response behind it is what a false positive looks like here.
    """
    import numpy as np

    p = sub["per_chain_distribution"]
    rows = json.loads(TELEMETRY.read_text())["rows"]
    by = {}
    for r in rows:
        if r["method"] in ("table_field", "p2rank") and r.get("residue_auc"):
            by.setdefault(r["method"], {})[r["unit_id"]] = float(r["residue_auc"])
    shared = sorted(set(by["table_field"]) & set(by["p2rank"]))
    d = np.sort(np.array([by["table_field"][u] - by["p2rank"][u]
                          for u in shared]))

    fig, (axl, axr) = plt.subplots(
        1, 2, figsize=(12.6, 5.2), gridspec_kw={"width_ratios": [1.0, 1.5]})

    axl.bar(np.arange(len(d)), d, width=1.0,
            color=["#d94801" if x > 0 else "#4a7fb0" for x in d], lw=0)
    axl.axhline(0, color="black", lw=0.9)
    axl.set_xlabel("chains, sorted by difference", fontsize=9.5)
    axl.set_ylabel("per-residue ROC-AUC, table field minus P2Rank",
                   fontsize=9.5)
    axl.text(0.03, 0.05,
             f"{p['n_baseline_ahead']} behind, {p['n_field_ahead']} ahead, "
             f"{p['n_tied']} tied\n"
             f"{p['n_losses_worse_than_5pct']} losses worse than 5 points, "
             f"{p['n_wins_better_than_5pct']} wins better\n"
             f"mean {p['mean']:+.4f}, median {p['quantiles']['0.5']:+.4f}, "
             f"sd {p['sd']:.4f}",
             transform=axl.transAxes, va="bottom", fontsize=8.3)
    axl.grid(axis="y", alpha=0.22, lw=0.5)
    axl.set_axisbelow(True)

    surviving = {(b["covariate"], b["band"]): b
                 for b in sub["bands_excluding_zero_after_correction"]}
    ys, labels = [], []
    y = 0
    for name in reversed(list(sub["by_covariate"])):
        v = sub["by_covariate"][name]
        for b in reversed(v["bands"]):
            hit = (name, b["band"]) in surviving
            colour = "#d94801" if hit else "#8c8c8c"
            axr.plot(b["ci_bonferroni"], [y, y], color=colour, lw=1.5,
                     alpha=0.42, solid_capstyle="butt")
            axr.plot(b["ci95"], [y, y], color=colour, lw=3.0,
                     solid_capstyle="butt")
            axr.plot(b["mean"], y, "o", color=colour, ms=6, zorder=3)
            ys.append(y)
            labels.append(f"{b['band']}  (n={b['n']})")
            y += 1
        # The row above each group carries its name and its trend test, so five
        # groups of three read as five groups and the trend sits with the bands
        # it qualifies rather than in a legend somewhere else. It has to be a
        # row of its own: written across the middle band it would collide with
        # that band's tick label.
        axr.text(-0.155, y, COV_LABEL[name], transform=axr.get_yaxis_transform(),
                 fontsize=9.2, va="center", ha="left", fontweight="bold")
        axr.text(1.0, y,
                 f"$\\rho$ {v['spearman_rho']:+.3f}, p={v['spearman_p_permutation']:.2f}",
                 transform=axr.get_yaxis_transform(), fontsize=8.0,
                 va="center", ha="right", color="#555555")
        y += 1

    axr.axvline(0, color="black", lw=1.0)
    axr.set_yticks(ys)
    axr.set_yticklabels(labels, fontsize=8.4)
    # Two rows of headroom below the lowest band for the annotation, so it does
    # not sit on top of the bar it is describing.
    axr.set_ylim(-2.6, y)
    axr.set_xlabel("mean paired difference within the band "
                   "(thick: 95%, thin: Bonferroni over 15)", fontsize=9.5)
    axr.grid(axis="x", alpha=0.22, lw=0.5)
    axr.set_axisbelow(True)
    for (cov, band), b in surviving.items():
        axr.text(-0.155, -1.7,
                 f"clears the corrected level: {COV_LABEL[cov]} {band}, "
                 f"{b['mean']:+.4f} [{b['ci'][0]:+.4f}, {b['ci'][1]:+.4f}].\n"
                 f"Its covariate's trend is null and the bands do not order, "
                 f"so nothing explains it.",
                 transform=axr.get_yaxis_transform(), ha="left", va="center",
                 fontsize=8.2, color="#d94801")

    fig.tight_layout()
    fig.subplots_adjust(left=0.075, wspace=0.30)
    out = FIGDIR / "fig_subgroups.png"
    fig.savefig(out, dpi=200)
    plt.close(fig)

    n_surv = len(surviving)
    n_trend = len(sub["trends_surviving_correction"])
    caption = (
        f"Where the two detectors differ on the {p['n']} chains of the fold, "
        f"and what survives asking. Left, one bar per chain, sorted: the field "
        f"is ahead on {p['n_field_ahead']}, behind on {p['n_baseline_ahead']} "
        f"and ties on {p['n_tied']}, but its losses reach further than its wins "
        f"\u2014 {p['n_losses_worse_than_5pct']} chains lose by more than five "
        f"ROC-AUC points against {p['n_wins_better_than_5pct']} that win by "
        f"more \u2014 which is why the mean ({p['mean']:+.4f}) sits below the "
        f"median ({p['quantiles']['0.5']:+.4f}). Right, the fold cut into "
        f"thirds by five covariates fixed before the read from the CryptoBench "
        f"deposit, the labels and the coordinates, with no score opened. Thick "
        f"bars are 95% intervals, thin bars Bonferroni over the "
        f"{sub['n_band_tests']} bands, and \u03c1 is the Spearman correlation "
        f"between the covariate and the per-chain difference, tested by "
        f"permutation. {n_surv} band clears the corrected level and "
        f"{n_trend} of five trends do; the surviving band sits between two that "
        f"do not order around it, so nothing here identifies a kind of protein "
        f"on which one detector is better. The analysis was preregistered as "
        f"exploratory and no result from it is claimed.")
    return out, caption


def figure_matched(read: dict) -> tuple[Path, str]:
    """What the F1 margin was, once the threshold was held in common.

    The left panel is the whole curve rather than the two points the analysis
    turns on, because the objection being answered is about a convention and a
    reader can only judge a convention by seeing the alternatives. The right
    panel puts the published difference and the matched one on one axis, which
    is the entire finding: the interval moves across zero and nothing else
    changes.
    """
    curve = read["f1_against_q"]
    q = [r["q"] for r in curve]
    ours = [r["table_field_f1"] for r in curve]
    theirs = [r["p2rank_f1"] for r in curve]
    nat = read["native_call_reference"]
    m = read["matched"]["B_each_tuned_on_train"]
    o = read["oracle"]
    q_ship = m["q_ours"]

    fig, (axc, axd) = plt.subplots(
        1, 2, figsize=(12.4, 4.0), gridspec_kw={"width_ratios": [1.25, 1.1]})

    axc.plot(q, ours, "-", color="#d94801", lw=2.0, label="Table field")
    axc.plot(q, theirs, "-", color="#2c7fb8", lw=2.0, label="P2Rank 2.5.1")
    axc.axvline(q_ship, color="black", lw=0.9, ls=":")
    axc.plot([q_ship], [m["table_field_f1"]], "o", color="#d94801", ms=7,
             zorder=3)
    axc.plot([q_ship], [m["p2rank_f1"]], "o", color="#2c7fb8", ms=7, zorder=3)
    # P2Rank's shipped call is not on the curve at all: it is a pocket
    # assignment, not a fraction of the chain, so it is drawn as a level.
    axc.axhline(nat["p2rank_f1"], color="#2c7fb8", lw=1.1, ls="--")
    axc.text(q[-1], nat["p2rank_f1"], " P2Rank's own\n pocket call",
             color="#2c7fb8", fontsize=8.2, va="center", ha="right")
    axc.text(q_ship, min(theirs) - 0.004,
             f" q={q_ship:.2f}, chosen on the training fold\n"
             f" by one grid search, for both methods",
             fontsize=8.2, va="bottom")
    axc.set_xlabel("q, the fraction of each chain called positive", fontsize=9.5)
    axc.set_ylabel("mean per-structure F1", fontsize=9.5)
    axc.legend(fontsize=8.8, loc="upper right", frameon=False)
    axc.grid(alpha=0.22, lw=0.5)
    axc.set_axisbelow(True)

    bars = [
        ("each method's own\noperating point",
         nat["published_delta"],
         read["native_call_reference"]["published_ci"][0],
         read["native_call_reference"]["published_ci"][1]),
        (f"both at q={q_ship:.2f}\n(the matched rule)",
         m["primary"]["delta_point"], m["primary"]["delta_ci_low"],
         m["primary"]["delta_ci_high"]),
        (f"P2Rank at its best q\non this fold ({o['p2rank_best_q_on_the_held_out_fold']:.2f})",
         o["our_shipped_q_vs_p2rank_oracle_q"]["delta_point"],
         o["our_shipped_q_vs_p2rank_oracle_q"]["delta_ci_low"],
         o["our_shipped_q_vs_p2rank_oracle_q"]["delta_ci_high"]),
    ]
    ys = list(range(len(bars)))[::-1]
    for y, (lab, pt, lo, hi) in zip(ys, bars):
        resolved = not (lo <= 0.0 <= hi)
        colour = "#d94801" if resolved else "#8c8c8c"
        axd.plot([lo, hi], [y, y], color=colour, lw=2.4, solid_capstyle="butt")
        axd.plot(pt, y, "o", color=colour, ms=7, zorder=3)
        axd.text(0.062, y,
                 f"{pt:+.4f}  [{lo:+.4f}, {hi:+.4f}]   "
                 f"{'resolved' if resolved else 'contains zero'}",
                 va="center", fontsize=8.6,
                 color="black" if resolved else "#555555")
    axd.axvline(0, color="black", lw=1.0)
    axd.set_yticks(ys)
    axd.set_yticklabels([b[0] for b in bars], fontsize=9.2)
    axd.set_xlabel("paired F1 difference, table field minus P2Rank",
                   fontsize=9.5)
    axd.set_xlim(-0.03, 0.20)
    axd.grid(axis="x", alpha=0.22, lw=0.5)
    axd.set_axisbelow(True)

    fig.tight_layout()
    out = FIGDIR / "fig_matched_operating_point.png"
    fig.savefig(out, dpi=200)
    plt.close(fig)

    caption = (
        f"The F1 margin over P2Rank, before and after holding the operating "
        f"point in common, on all {read['n_units']} held-out structures. Left, "
        f"mean per-structure F1 as a function of the fraction q of each chain "
        f"called positive, for both methods. The dashed level is P2Rank's own "
        f"pocket assignment, which is not a point on the curve because it is "
        f"not a fraction of the chain; the published comparison is that level "
        f"against our curve at q={q_ship:.2f}. Running the grid search that "
        f"chose our q on P2Rank's training scores returns the same "
        f"q={q_ship:.2f}, so the two matched rules a reader might ask for "
        f"coincide. Right, the paired difference under each convention with 95% "
        f"bootstrap intervals: {nat['published_delta']:+.4f} at the shipped "
        f"operating points, {m['primary']['delta_point']:+.4f} "
        f"[{m['primary']['delta_ci_low']:+.4f}, "
        f"{m['primary']['delta_ci_high']:+.4f}] once both are binarised the "
        f"same way, and {o['our_shipped_q_vs_p2rank_oracle_q']['delta_point']:+.4f} "
        f"against P2Rank at the best q this fold admits \u2014 an upper bound it "
        f"could not have known. Our own F1 is identical in the first two "
        f"columns: our shipped call already is the matched rule at this q. The "
        f"rules and the sentence to be written under each outcome were "
        f"committed in "
        f"{read['ordering']['preregistration_commit'][:7]} before the fold was "
        f"read for them.")
    return out, caption


def figure_full_metrics(read: dict) -> tuple[Path, str]:
    """Where the margin lived, and where it went once the budget was matched.

    The left panel is the only picture that answers the objection directly: at
    each detector's own operating point the two arms sit at different points of
    one precision--recall trade, and at a matched budget they sit at the same
    calling cost so the comparison is between rankings. The right panel is the
    whole interval grid rather than a chosen row of it, because forty-eight
    intervals were computed and showing four of them would be the selection the
    multiplicity block exists to prevent.
    """
    convs = ["D1_as_deployed", "D2_common_budget", "D4_each_tuned_for_mcc"]
    labels = {"D1_as_deployed": "as deployed",
              "D2_common_budget": "common budget",
              "D4_each_tuned_for_mcc": "each tuned for MCC"}
    fig, (axp, axi) = plt.subplots(
        1, 2, figsize=(12.4, 4.3), gridspec_kw={"width_ratios": [1.0, 1.35]})

    marks = {"D1_as_deployed": "o", "D2_common_budget": "s",
             "D4_each_tuned_for_mcc": "^"}
    for cid in convs:
        e = read["conventions"][cid]
        for arm, colour in (("table_field", "#d94801"), ("p2rank", "#2c7fb8")):
            axp.plot(e[arm]["recall"], e[arm]["precision"], marks[cid],
                     color=colour, ms=9, zorder=3)
        # The pair under one convention is one comparison, so it is joined.
        axp.plot([e["table_field"]["recall"], e["p2rank"]["recall"]],
                 [e["table_field"]["precision"], e["p2rank"]["precision"]],
                 "-", color="#999999", lw=1.0, zorder=2)
    # Each marker is labelled by the threshold it is, not by the convention that
    # asked for it. Two conventions leave our point where it was and two leave
    # P2Rank's where it was, so convention names on the markers would put two
    # labels on one dot and read as though something had moved.
    d1, d2, d4 = (read["conventions"][c] for c in convs)
    for arm, e, text, off, colour in (
            ("table_field", d2, f"table field, top-{d2['q_ours']:.0%}"
                                f"\n(as deployed and common budget)",
             (12, 6), "#a04000"),
            ("table_field", d4, f"table field, top-{d4['q_ours']:.0%}"
                                f"\n(MCC-tuned)", (10, -6), "#a04000"),
            ("p2rank", d1, "P2Rank, its own\npocket assignment", (-10, 12),
             "#1f5f8b"),
            ("p2rank", d2, f"P2Rank, top-{d2['q_p2rank']:.0%}\n(both matched "
                           f"conventions)", (12, -10), "#1f5f8b")):
        axp.annotate(text, (e[arm]["recall"], e[arm]["precision"]),
                     fontsize=8.0, textcoords="offset points", xytext=off,
                     color=colour)
    for cid in convs:
        axp.plot([], [], marks[cid], color="#666666", ms=8, label=labels[cid])
    axp.plot([], [], "o", color="#d94801", ms=8, label="Table field")
    axp.plot([], [], "o", color="#2c7fb8", ms=8, label="P2Rank 2.5.1")
    axp.set_xlabel("mean per-structure recall", fontsize=9.5)
    axp.set_ylabel("mean per-structure precision", fontsize=9.5)
    axp.legend(fontsize=8.2, loc="lower left", frameon=False, ncol=1)
    axp.grid(alpha=0.22, lw=0.5)
    axp.set_axisbelow(True)
    axp.margins(0.16)

    metric_order = ["precision", "recall", "positive_class_f1", "mcc"]
    nice = {"precision": "precision", "recall": "recall",
            "positive_class_f1": "F1", "mcc": "MCC"}
    ys, ylabels = [], []
    y = 0
    for cid in convs:
        for met in metric_order:
            p = read["conventions"][cid]["paired"][met]["chain"]
            if p["delta_point"] is None:
                continue
            resolved = not p["crosses_zero"]
            governed = met in read["multiplicity"]["governed"]
            colour = ("#d94801" if resolved and governed
                      else "#e6a86b" if resolved else "#8c8c8c")
            axi.plot([p["delta_ci_low"], p["delta_ci_high"]], [y, y],
                     color=colour, lw=2.4, solid_capstyle="butt")
            axi.plot(p["delta_point"], y, "o", color=colour, ms=6.5, zorder=3)
            ys.append(y)
            ylabels.append(f"{labels[cid]}: {nice[met]}")
            y -= 1
        y -= 0.5
    axi.axvline(0, color="black", lw=1.0)
    axi.set_yticks(ys)
    axi.set_yticklabels(ylabels, fontsize=8.6)
    axi.set_xlabel("paired difference, table field minus P2Rank", fontsize=9.5)
    axi.grid(axis="x", alpha=0.22, lw=0.5)
    axi.set_axisbelow(True)
    # A legend rather than a text block: the block sat on top of the last two
    # rows, and what the colours mean is a key, not a caption.
    for colour, lab in (("#d94801", "excludes zero, a preregistered rule "
                                    "governs it"),
                        ("#e6a86b", "excludes zero, no rule governs it"),
                        ("#8c8c8c", "contains zero")):
        axi.plot([], [], "-", color=colour, lw=2.4, marker="o", ms=6.5,
                 label=lab)
    axi.legend(fontsize=7.8, loc="lower left", frameon=False)
    axi.set_ylim(min(ys) - 1.4, max(ys) + 0.8)

    fig.tight_layout()
    out = FIGDIR / "fig_matched_full_metrics.png"
    fig.savefig(out, dpi=200)
    plt.close(fig)

    w = read["where_the_deployment_rule_margin_came_from"]
    d1 = read["conventions"]["D1_as_deployed"]
    d2 = read["conventions"]["D2_common_budget"]
    rec = d2["paired"]["recall"]["chain"]
    worst = max(v[u]["ratio_to_chain"]
                for v in read["ci_width_by_resampling_unit"].values()
                for u in ("pdb_entry", "uniprot_cluster")
                if v[u]["ratio_to_chain"] is not None)
    caption = (
        f"Where the reported margin came from, on all {read['n_units']} "
        f"held-out structures. Left, the two detectors in the precision--recall "
        f"plane under three conventions, each pair joined by a line. Run as "
        f"delivered, P2Rank calls "
        f"{w['p2rank_calls_this_many_times_as_many']:.2f} times as many "
        f"residues as our rule does "
        f"({d1['n_residues_called']['p2rank']} against "
        f"{d1['n_residues_called']['table_field']}), which buys recall and "
        f"costs precision: our precision is higher by "
        f"{d1['paired']['precision']['chain']['delta_point']:+.4f} and our "
        f"recall lower by "
        f"{d1['paired']['recall']['chain']['delta_point']:+.4f}, both intervals "
        f"excluding zero. At a common budget both call "
        f"{d2['n_residues_called']['table_field']} residues and the trade is "
        f"gone. Right, every paired difference with a 95% bootstrap interval "
        f"over structures. The F1 and MCC differences remain positive and "
        f"contain zero under every matched convention. The matched recall "
        f"difference, {rec['delta_point']:+.4f} "
        f"[{rec['delta_ci_low']:+.4f}, {rec['delta_ci_high']:+.4f}], excludes "
        f"zero at p={rec['p_two_sided_bootstrap']:.3f}, which does not survive "
        f"a Bonferroni threshold of "
        f"{read['multiplicity']['bonferroni_alpha_over_the_four_metrics_of_one_convention']:.4f} "
        f"over the four metrics of one convention and carried no preregistered "
        f"decision rule; it is an observation about this fold and is drawn as "
        f"one. Resampling PDB entries or MMseqs2 clusters instead of chains "
        f"changes no interval here by more than a factor of {worst:.3f}.")
    return out, caption


def _projection(coords: dict[int, "np.ndarray"]):
    """The chain flattened onto its own two longest axes.

    A ribbon rendering would say more, and would need a structure viewer, a
    session file and a hand-chosen camera for each case -- three things that
    cannot be regenerated by a Makefile and cannot be checked by CI. The
    principal-axis projection is chosen by the coordinates rather than by the
    author, and it is enough for the only question these panels ask: did the
    method put its calls where the pocket is.
    """
    import numpy as np
    keys = sorted(coords)
    xyz = np.array([coords[k] for k in keys])
    centred = xyz - xyz.mean(axis=0)
    _, _, vt = np.linalg.svd(centred, full_matrices=False)
    return keys, centred @ vt[:2].T


def figure_cases(cases: dict) -> tuple[Path, str]:
    import sys
    sys.path.insert(0, str(ROOT / "tools"))
    from select_case_studies import ca_coords  # noqa: PLC0415

    rows = [("table_field", "Table field", "#d94801"),
            ("p2rank", "P2Rank 2.5.1", "#2c7fb8")]
    picked = cases["cases"]
    fig, axes = plt.subplots(len(rows), len(picked),
                             figsize=(2.9 * len(picked), 6.6))
    for col, case in enumerate(picked):
        coords = ca_coords(case["unit_id"])
        keys, xy = _projection(coords)
        index = {k: i for i, k in enumerate(keys)}
        truth = [index[r] for r in case["cryptic_residues"] if r in index]
        # Square limits and a square box: the projection stays undistorted, and
        # every panel is the same shape, which an equal-aspect autoscale does
        # not give and which the column labels need in order to line up.
        half = float(abs(xy).max()) * 1.06
        for row, (method, label, colour) in enumerate(rows):
            ax = axes[row][col]
            ax.scatter(xy[:, 0], xy[:, 1], s=5, c="#dddddd", linewidths=0)
            ax.scatter(xy[truth, 0], xy[truth, 1], s=42,
                       facecolors="none", edgecolors="black", linewidths=0.9)
            called = [index[r] for r in case["called_residues"][method]
                      if r in index]
            ax.scatter(xy[called, 0], xy[called, 1], s=13, c=colour,
                       linewidths=0)
            ax.set_xlim(-half, half)
            ax.set_ylim(-half, half)
            ax.set_box_aspect(1)
            ax.set_xticks([])
            ax.set_yticks([])
            for side in ax.spines.values():
                side.set_color("#bbbbbb")
            if col == 0:
                ax.set_ylabel(label, fontsize=10)
            geom = (case["geometry"]["methods"].get(method) or {})
            offset = geom.get("centroid_offset_angstrom")
            ax.set_xlabel(
                f"F1 {case['f1'][method]:.2f}" +
                ("" if offset is None else
                 f",  {offset:.0f} \u00c5 off centre"), fontsize=8.5)

    fig.subplots_adjust(left=0.055, right=0.99, top=0.99, bottom=0.135,
                        wspace=0.10, hspace=0.22)
    for col, case in enumerate(picked):
        box = axes[-1][col].get_position()
        fig.text((box.x0 + box.x1) / 2, 0.055,
                 f"{case['unit_id']}\n{case['case'].replace('_', ' ')}",
                 ha="center", va="top", fontsize=9.5)
    out = FIGDIR / "fig_case_studies.png"
    fig.savefig(out, dpi=200)
    plt.close(fig)

    pop = cases["population"]
    caption = (
        f"Four evaluation units, projected onto each chain's two longest "
        f"principal axes: grey is the chain, black rings are the labelled "
        f"cryptic residues, filled points are the residues each method called "
        f"positive. The cases are chosen by rule and not by eye -- the "
        f"clearest joint success, the largest margin each way, and the largest "
        f"labelled pocket among the units neither method locates -- where "
        f"locating means per-residue F1 at least "
        f"{cases['locate_threshold_f1']:g}. That last case is the commonest "
        f"outcome: of {pop['n_units']} units, {pop['n_located_by_both']} are "
        f"located by both methods, "
        f"{pop['n_located_by_table_field'] - pop['n_located_by_both']} by the "
        f"table field only, "
        f"{pop['n_located_by_p2rank'] - pop['n_located_by_both']} by P2Rank "
        f"only, and {pop['n_located_by_neither']} by neither.")
    return out, caption


def _sha(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def readme_block(drawn: list[tuple[Path, str]]) -> str:
    """The images and their captions, in the form the README carries them.

    Generated rather than typed, for the reason every other number here is:
    a caption states counts, seeds and a standard error, and a hand-written one
    goes stale the first time the fold is rescored. Captions sit under their
    image because that is where a reader of the manuscript will look for them,
    and nothing is drawn on top of the plot itself.
    """
    out = [BEGIN, ""]
    for i, (path, caption) in enumerate(drawn, 1):
        out.append(f"![Figure {i}](figures/{path.name})")
        out.append("")
        out.append(f"**Figure {i}.** {caption}")
        out.append("")
    out.append(END)
    return "\n".join(out)


def _write_readme(drawn: list[tuple[Path, str]]) -> bool:
    text = README.read_text()
    if BEGIN not in text or END not in text:
        print(f"README is missing the figure markers:\n  {BEGIN}\n  {END}")
        return False
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    README.write_text(head + readme_block(drawn) + tail)
    return True


COARSE_ORDER = ("geometric", "spatial smoothing", "density field", "topological",
                "chemical")
COARSE_COLOUR = {"geometric": "#d94801", "spatial smoothing": "#fdae61",
                 "density field": "#7fcdbb", "topological": "#2c7fb8",
                 "chemical": "#984ea3"}
CLASS_ORDER = (("called and labelled", "found"),
               ("labelled and missed", "missed"),
               ("called and not labelled", "false alarm"))


def _pocket_camera(xyz, pocket_rows):
    """A camera chosen by the coordinates, not by the author.

    The view direction is the vector from the chain's centroid to the labelled
    pocket's centroid, so the pocket faces the reader. A hand-posed camera would
    say more and could not be regenerated by a Makefile or checked in CI, which is
    the objection ``_projection`` was written to avoid; a rule that points the
    camera at the thing under discussion keeps the 3-D view and answers it.
    """
    import numpy as np
    v = xyz[pocket_rows].mean(axis=0) - xyz.mean(axis=0)
    n = float(np.linalg.norm(v))
    if n < 1e-9:
        return 18.0, -60.0
    v = v / n
    elev = float(np.degrees(np.arcsin(max(-1.0, min(1.0, v[2])))))
    azim = float(np.degrees(np.arctan2(v[1], v[0])))
    return elev, azim


def figure_structural_cases(cases: dict, audit: dict) -> tuple[Path, str]:
    """The two chains where the methods disagree, in three dimensions.

    Chosen by rule, not by eye: the case that ``CASE_STUDIES.json`` labels
    ``table_field_only`` and the one it labels ``p2rank_only``. Those are the only
    two chains on which one method locates the site and the other does not, so
    they are the success and the failure whatever the figure shows.

    Each row asks the three questions a reader who works on proteins would ask.
    Where is the labelled cryptic site. Where did each method put its calls. And,
    for our method, which families of the score put them there -- read from
    ``AUDIT_DECOMPOSITION.json`` rather than recomputed, so the panel and the text
    cannot disagree.
    """
    import sys

    import numpy as np
    sys.path.insert(0, str(ROOT / "tools"))
    from select_case_studies import ca_coords  # noqa: PLC0415

    by_case = {c["case"]: c for c in cases["cases"]}
    picked = [by_case[k] for k in ("table_field_only", "p2rank_only")
              if k in by_case]
    dec = {c["unit_id"]: c for c in audit.get("cases", [])}
    methods = (("table_field", "Counting field", "#d94801"),
               ("p2rank", "P2Rank 2.5.1", "#2c7fb8"))

    fig = plt.figure(figsize=(11.4, 3.7 * len(picked)))
    first_column: list = []
    for row, case in enumerate(picked):
        row_axes: list = []
        coords = ca_coords(case["unit_id"])
        keys = sorted(coords)
        index = {k: i for i, k in enumerate(keys)}
        xyz = np.array([coords[k] for k in keys])
        truth = [index[r] for r in case["cryptic_residues"] if r in index]
        elev, azim = _pocket_camera(xyz, truth or list(range(len(keys))))
        centre = xyz.mean(axis=0)
        half = float(np.abs(xyz - centre).max()) * 1.02

        for col, (method, label, colour) in enumerate(methods):
            ax = fig.add_subplot(len(picked), 3, row * 3 + col + 1,
                                 projection="3d")
            ax.plot(xyz[:, 0], xyz[:, 1], xyz[:, 2], color="#d9d9d9", lw=0.8)
            ax.scatter(xyz[:, 0], xyz[:, 1], xyz[:, 2], s=3, c="#bdbdbd",
                       linewidths=0, depthshade=False)
            if truth:
                ax.scatter(xyz[truth, 0], xyz[truth, 1], xyz[truth, 2], s=64,
                           facecolors="none", edgecolors="black", linewidths=1.0,
                           depthshade=False)
            called = [index[r] for r in case["called_residues"][method]
                      if r in index]
            if called:
                ax.scatter(xyz[called, 0], xyz[called, 1], xyz[called, 2], s=26,
                           c=colour, linewidths=0, depthshade=False)
            ax.view_init(elev=elev, azim=azim)
            for a, c in ((ax.set_xlim, 0), (ax.set_ylim, 1), (ax.set_zlim, 2)):
                a(centre[c] - half, centre[c] + half)
            # A cube keeps the three axes on one scale, so the shape is the
            # protein's and not the layout's; the zoom only fills the panel.
            ax.set_box_aspect((1, 1, 1), zoom=1.32)
            ax.set_axis_off()
            row_axes.append(ax)
            geom = (case["geometry"]["methods"].get(method) or {})
            off = geom.get("centroid_offset_angstrom")
            near = geom.get("fraction_within_8a_of_pocket")
            ax.set_title(
                f"{label}\nF1 {case['f1'][method]:.2f}"
                + ("" if off is None else f",  centre {off:.1f} \u00c5 off")
                + ("" if near is None else f",  {near:.0%} within 8 \u00c5"),
                fontsize=8.6, pad=0)

        first_column.append(row_axes[0])
        ax = fig.add_subplot(len(picked), 3, row * 3 + 3)
        d = dec.get(case["unit_id"], {}).get(
            "mean_contribution_by_residue_class", {})
        rows_drawn = [(cls, short) for cls, short in CLASS_ORDER if cls in d]
        h = 0.8 / max(len(rows_drawn), 1)
        for i, (cls, short) in enumerate(rows_drawn):
            left_pos = left_neg = 0.0
            for fam in COARSE_ORDER:
                v = float(d[cls].get(fam, 0.0))
                base = left_pos if v >= 0 else left_neg
                ax.barh(-i, v, left=base, height=h,
                        color=COARSE_COLOUR[fam], linewidth=0,
                        label=fam if i == 0 else None)
                if v >= 0:
                    left_pos += v
                else:
                    left_neg += v
            ax.text(0, -i + h * 0.80, f"{short}  (n={d[cls]['n']})",
                    fontsize=8, ha="left", va="bottom", color="#333333")
        ax.axvline(0, color="black", lw=0.8)
        ax.set_yticks([])
        ax.set_ylim(-len(rows_drawn) + 0.40, 1.10)
        ax.set_xlabel("contribution to the score, by family", fontsize=8.5)
        ax.tick_params(labelsize=8)
        for side in ("top", "right", "left"):
            ax.spines[side].set_visible(False)
        legend_ax = ax if row == len(picked) - 1 else None

    handles, labels = fig.axes[2].get_legend_handles_labels()
    fig.subplots_adjust(left=0.005, right=0.985, top=0.885, bottom=0.115,
                        wspace=0.02, hspace=0.42)
    if handles:
        fig.legend(handles, labels, fontsize=8, ncol=len(labels),
                   loc="lower center", frameon=False,
                   bbox_to_anchor=(0.5, 0.005))
    # Anchored below the panels, where nothing else is drawn: a heading placed
    # above them rides over the method titles as soon as the layout moves.
    for ax0, case in zip(first_column, picked):
        box = ax0.get_position()
        fig.text(box.x0 + 0.02, box.y0 + 0.035,
                 f"{case['unit_id']}  \u2014  {case['why_this_one']}",
                 fontsize=9.6, va="bottom", ha="left", color="#222222")
    out = FIGDIR / "fig_structural_cases.png"
    fig.savefig(out, dpi=200)
    plt.close(fig)

    names = " and ".join(c["unit_id"] for c in picked)
    return out, (
        f"The two chains on which the methods disagree, {names}, chosen by the "
        f"rule in CASE_STUDIES.json rather than by eye. Black rings are the "
        f"labelled cryptic residues; filled points are what each method called. "
        f"The camera looks from the chain's centroid towards the labelled "
        f"pocket, so the view is fixed by the coordinates and not by the author. "
        f"The right-hand panels decompose our own score on that chain into the "
        f"five coarse families, separately for the labelled residues we found, "
        f"the labelled residues we missed, and the residues we called that are "
        f"not labelled, read from AUDIT_DECOMPOSITION.json.")


def figure_threshold_curve(curve: dict) -> tuple[Path, str]:
    """Every calling fraction, because three of them cannot say they were typical.

    The left panel is the level of each method and the right is the paired
    difference against ours, so the two questions a reader has -- how good is it,
    and is it better than that one -- are not answered by the same line. Both
    baselines and the field are drawn on one axis rather than one panel each: the
    point of the figure is the ordering, and an ordering split across panels has
    to be reassembled by eye.

    Nothing is marked as the best point of any curve, on purpose. The plan behind
    this read forbids choosing from it, and an annotated maximum is how that
    prohibition would quietly stop being true.
    """
    arms = curve["arms"]
    style = {"p2rank": ("#2c7fb8", "P2Rank 2.5.1"),
             "pocketminer": ("#7b3294", "PocketMiner"),
             "plmnn": ("#1a9850", "pLM-NN (CryptoBench's own)")}
    fig, (axl, axr) = plt.subplots(1, 2, figsize=(12.4, 4.4))

    ref = arms["p2rank"]["curve"]
    qs = [r["q"] for r in ref]
    axl.plot(qs, [r["positive_class_f1"]["ours"] for r in ref], "-",
             color="#d94801", lw=2.4, label="Table field (ours)", zorder=4)
    for name, arm in arms.items():
        colour, label = style[name]
        axl.plot([r["q"] for r in arm["curve"]],
                 [r["positive_class_f1"]["theirs"] for r in arm["curve"]],
                 "-", color=colour, lw=1.8, label=label)
    deployed = curve["selects_nothing"]["deployed_q_unchanged"]
    for ax in (axl, axr):
        ax.axvline(deployed, color="#555555", lw=0.9, ls=":", zorder=1)
        ax.grid(alpha=0.22, lw=0.5)
        ax.set_axisbelow(True)
        ax.set_xlabel("fraction of each chain called positive", fontsize=9.5)
    axl.annotate(f"deployed rule, top-{deployed:.0%}\n(chosen on the training "
                 f"fold)", (deployed, axl.get_ylim()[0]), fontsize=7.8,
                 textcoords="offset points", xytext=(6, 16), color="#555555")
    axl.set_ylabel("mean per-structure positive-class F1", fontsize=9.5)
    axl.legend(fontsize=8.2, loc="lower right", frameon=False)

    for name, arm in arms.items():
        colour, label = style[name]
        cq = [r["q"] for r in arm["curve"]]
        mean = [r["positive_class_f1"]["mean"] for r in arm["curve"]]
        lo = [r["positive_class_f1"]["ci"][0] for r in arm["curve"]]
        hi = [r["positive_class_f1"]["ci"][1] for r in arm["curve"]]
        axr.fill_between(cq, lo, hi, color=colour, alpha=0.16, lw=0)
        axr.plot(cq, mean, "-", color=colour, lw=2.0, label=f"minus {label}")
    axr.axhline(0, color="black", lw=1.0)
    axr.set_ylabel("paired difference in F1, ours minus theirs", fontsize=9.5)
    axr.legend(fontsize=8.2, loc="center right", frameon=False)

    fig.tight_layout()
    out = FIGDIR / "fig_threshold_curve.png"
    fig.savefig(out, dpi=200)
    plt.close(fig)

    sp = arms["p2rank"]["sign_span"]["positive_class_f1"]
    excl = sum(1 for r in ref if r["positive_class_f1"]["excludes_zero"])
    behind = [n for n, a in arms.items()
              if a["sign_span"]["positive_class_f1"]["n_where_theirs_is_higher"]
              == a["sign_span"]["positive_class_f1"]["n_cut_points"]]
    tail = ""
    if behind:
        names = " and ".join(style[n][1] for n in behind)
        tail = (f" {names} is ahead of the field at every cut point as well, and "
                f"by margins whose pointwise intervals exclude zero throughout, "
                f"so that deficit is no more a threshold artefact than the "
                f"advantage over P2Rank is.")
    return out, (
        f"The same frozen scores binarised at all {curve['grid']['n']} calling "
        f"fractions from {curve['grid']['low']:.0%} to {curve['grid']['high']:.0%}"
        f", on {arms['p2rank']['n_units']} held-out structures. Left, the level "
        f"each method reaches. Right, the paired difference against the counting "
        f"field with a pointwise 95% bootstrap band. Against P2Rank the field is "
        f"ahead at {sp['n_where_ours_is_higher']} of {sp['n_cut_points']} cut "
        f"points with {sp['sign_changes']} sign changes, so the F1 advantage "
        f"reported at the deployed rule is not an artefact of where the two "
        f"methods were cut; the pointwise interval excludes zero at {excl} of "
        f"them, all at calling fractions well above anything one would deploy, "
        f"so this is a statement about the sign of the difference rather than its "
        f"significance.{tail} No point on any curve was selected: the deployed "
        f"fraction was fixed on the training fold and this read feeds no "
        f"configuration, which is what keeps {curve['grid']['n']} cut points from "
        f"being {curve['grid']['n']} chances to find a favourable one.")


def figure_emdb_resolution() -> tuple[Path, str] | None:
    """Register the EMDB resolution comparison, redrawing it only if the data is here.

    The two density volumes are 139 MB and gitignored, so a fresh checkout holds
    the committed image and not what it was drawn from. Dropping the figure in
    that case would rewrite FIGURE_PROVENANCE.json without it and then fail the
    gate on the committed PNG, so instead the committed bytes are kept and
    registered as they are. Drift is still caught, by the source digest over
    EMDB_MAPS.json: change the asserted method or resolution and the gate demands
    a redraw, which needs the volumes back.

    The drawing itself lives in tools/fig_emdb_resolution.py, which owns the MRC
    reader and the axis permutation. Only the registration is here, because this
    is the file the figure gate reads to learn which images are legitimate.
    """
    import sys
    sys.path.insert(0, str(ROOT / "tools"))
    import fig_emdb_resolution as f

    out = FIGDIR / "fig_emdb_resolution.png"
    if f.maps_present():
        f.render(out)
    elif not out.exists():
        return None
    return out, f.caption()



def figure_external_difficulty(doc: dict) -> tuple[Path, str]:
    """Is the external set easier? The two answers, side by side.

    A reviewer's objection was that a 57-unit external set may simply be easier
    than the benchmark, which would make the paper's one confirmatory accuracy
    result cheaper than it looks. The objection is checkable two ways and they
    disagree, so both panels are drawn. Showing either alone would be the
    selection the ladder figures elsewhere in this repository exist to avoid.

    Left: the three quantities that control how hard a per-unit ranking problem
    is, as ratios of external to official. Bars to the right of 1 are the
    external set being harder. All three are.

    Right: what each method actually scored on each set. The ordering of the
    gains is the finding -- a uniformly easier set lifts every method, and this
    one lifts a local surface detector by +0.004 and a whole-sequence model by
    +0.052, in the order of how much context each reads. The panel is annotated
    with that reading rather than leaving a reader to infer it, because the
    ordering is the whole argument and it is not visible from the bar heights
    alone.
    """
    import numpy as np

    g = doc["label_geometry"]
    a = doc["achieved_accuracy"]
    off_g, ext_g = g["official_test_fold"], g["external_set_a"]

    axes = [
        ("residues to rank\n(chain length)",
         ext_g["chain_length"]["median"] / off_g["chain_length"]["median"],
         "longer chains, more negatives"),
        ("pocket size\n(cryptic residues)",
         off_g["cryptic_residues"]["median"] / ext_g["cryptic_residues"]["median"],
         "smaller pockets; measured effect 0.28"),
        ("positive sparsity\n(1 / positive rate)",
         off_g["positive_rate"]["median"] / ext_g["positive_rate"]["median"],
         "sparser positives"),
    ]

    fig, (axl, axr) = plt.subplots(
        1, 2, figsize=(12.6, 4.5), gridspec_kw={"width_ratios": [1.0, 1.25]})

    y = np.arange(len(axes))[::-1]
    axl.barh(y, [v for _n, v, _w in axes], height=0.5, color="#7b3294",
             zorder=2)
    axl.axvline(1.0, color="#444444", lw=1.2)
    for k, (_n, v, why) in enumerate(axes):
        axl.text(v + 0.012, y[k], f"{v:.2f}x   {why}", fontsize=8.4,
                 va="center")
    axl.set_yticks(y)
    axl.set_yticklabels([n for n, _v, _w in axes], fontsize=9.0)
    axl.set_xlim(0.9, max(v for _n, v, _w in axes) * 1.55)
    axl.set_xlabel("external / official, medians \u2014 right of 1 is harder",
                   fontsize=9.5)
    axl.grid(axis="x", alpha=0.2, lw=0.5)
    axl.set_axisbelow(True)

    order = sorted(a["external_minus_official"],
                   key=lambda k: a["external_minus_official"][k])
    labels = {"p2rank": "P2Rank\nlocal surface",
              "pocketminer": "PocketMiner\nstructure graph",
              "table_field": "counting field\n645 wires to 20 \u00c5",
              "plmnn": "pLM-NN\nwhole sequence"}
    x = np.arange(len(order))
    off = [a["official_test_fold"][k] for k in order]
    ext = [a["external_set_a"][k] for k in order]
    axr.bar(x - 0.19, off, width=0.36, color="#999999", zorder=2,
            label="official CryptoBench test fold")
    axr.bar(x + 0.19, ext, width=0.36, color="#1a6b1a", zorder=2,
            label="external set A")
    for k, key in enumerate(order):
        d = a["external_minus_official"][key]
        axr.annotate(f"{d:+.4f}", (x[k], max(off[k], ext[k]) + 0.006),
                     ha="center", fontsize=8.6,
                     color="#8b1a1a" if d < 0.01 else "#1a6b1a")
    axr.set_xticks(x)
    axr.set_xticklabels([labels.get(k, k) for k in order], fontsize=8.4)
    axr.set_ylim(0.70, 0.94)
    axr.set_ylabel("mean per-unit ROC-AUC", fontsize=9.5)
    axr.legend(fontsize=8.3, loc="upper left", frameon=False)
    axr.grid(axis="y", alpha=0.2, lw=0.5)
    axr.set_axisbelow(True)
    # Below the axis, not inside it. Placed at the foot of the panel this note
    # sat behind the bars, which is where the reader's eye already is.
    axr.set_xlabel(
        "the gain rises with how much context a method reads;\n"
        "a uniformly easier set would lift the leftmost bar too",
        fontsize=8.8, color="#333333", labelpad=6)

    fig.tight_layout()
    out = FIGDIR / "fig_external_difficulty.png"
    fig.savefig(out, dpi=200)
    plt.close(fig)

    p2 = a["external_minus_official"]["p2rank"]
    plm = a["external_minus_official"]["plmnn"]
    caption = (
        f"Whether the external set is easier than the benchmark, asked two ways "
        f"that disagree. Left: the three quantities controlling how hard a "
        f"per-unit ranking problem is, as external-over-official ratios of "
        f"medians; the external set has longer chains, smaller pockets and "
        f"sparser positives, so by label geometry it is harder on all three. "
        f"Pocket size is not a guess about difficulty \u2014 "
        f"FAILURE_TAIL.json measures the deployed field at 0.5991 on units with "
        f"under ten cryptic residues against 0.8766 above twenty-two. Right: "
        f"what each method scored on each set, from reads already indexed and "
        f"not recomputed. Three of four score higher externally, which is the "
        f"reviewer's reading and has support; the discriminating case is that "
        f"P2Rank, which reads local surface geometry, moves {p2:+.4f} while "
        f"pLM-NN, which reads the whole sequence, moves {plm:+.4f}. A uniformly "
        f"easier set lifts a local detector too. The honest statement is that "
        f"the set is not uniformly easier but rewards context, that any method "
        f"compared on it inherits that, and that 57 positive units is small "
        f"whichever way the difficulty goes.")
    return out, caption



def figure_setbc_read(read: dict, diff: dict) -> tuple[Path, str]:
    """The second external read, and the one thing it did settle.

    Left: the four comparisons the plan fixed, as intervals. The bar that matters
    is the top one and it crosses zero -- the training-fold estimate is drawn as a
    tick so a reader can see that the interval contains it and also contains its
    negation. A panel showing only the point estimates would make a
    does-not-resolve look like a small positive result, which is the reading the
    preregistration exists to prevent.

    Right: each method's level on the official fold and on these units. The
    confound named before the read was that longer chains would inflate whichever
    detector reads further, with P2Rank as the control. The control fell by 0.041
    and so did every other coordinate-reading method, while the sequence model
    rose by 0.044. That is a modality effect, it explains the levels, and it does
    not touch the difference in the left panel -- which is why both are drawn and
    the caption says which is which.
    """
    import numpy as np

    order = [("deployed detector", "geometry_field_minus_table_field"),
             ("pLM-NN", "geometry_field_minus_plmnn"),
             ("P2Rank", "geometry_field_minus_p2rank"),
             ("PocketMiner", "geometry_field_minus_pocketminer")]
    fig, (axl, axr) = plt.subplots(
        1, 2, figsize=(12.8, 4.6), gridspec_kw={"width_ratios": [1.25, 1.0]})

    y = np.arange(len(order))[::-1]
    for k, (label, key) in enumerate(order):
        b = read["co_primary"][key]
        lo, hi = b["ci"]
        blo, bhi = b["ci_bonferroni"]
        resolves = not (lo <= 0 <= hi)
        colour = "#1a6b1a" if resolves and b["mean"] > 0 else \
                 "#8b1a1a" if resolves else "#888888"
        axl.plot([blo, bhi], [y[k]] * 2, color=colour, lw=1.4, alpha=0.45,
                 solid_capstyle="butt")
        axl.plot([lo, hi], [y[k]] * 2, color=colour, lw=3.4,
                 solid_capstyle="butt")
        axl.plot(b["mean"], y[k], "o", ms=7, color=colour, zorder=3)
        axl.plot(b["predicted"], y[k], "|", ms=15, mew=2.0, color="#d95f02",
                 zorder=4)
        axl.text(hi + 0.004, y[k] + 0.17,
                 f"{b['mean']:+.4f}   {b['n_first_ahead']}/"
                 f"{b['n_second_ahead']} units", fontsize=8.4, va="center")
        axl.text(hi + 0.004, y[k] - 0.20, b["verdict"].replace("_", " "),
                 fontsize=8.2, va="center", color=colour)
    axl.axvline(0, color="#333333", lw=1.2)
    axl.set_yticks(y)
    axl.set_yticklabels([lab for lab, _k in order], fontsize=9.4)
    # "the four-family stack", not a column count taken from the unit count --
    # the first version read n_units_compared and labelled the axis "the
    # 45-column stack", which is a factual error in a figure rather than a
    # cosmetic one.
    axl.set_xlabel("the four-family stack minus each method,\n"
                   "mean paired per-unit ROC-AUC", fontsize=9.4)
    axl.set_xlim(-0.16, 0.20)
    axl.grid(axis="x", alpha=0.2, lw=0.5)
    axl.set_axisbelow(True)
    axl.legend(handles=[
        plt.Line2D([], [], color="#888888", lw=3.4, label="95 % interval"),
        plt.Line2D([], [], color="#888888", lw=1.4, alpha=0.45,
                   label="Bonferroni over four"),
        plt.Line2D([], [], marker="|", ls="", color="#d95f02", ms=13, mew=2.0,
                   label="pinned prediction"),
    ], fontsize=8.2, loc="lower left", frameon=False)

    official = {"table_field": 0.799105, "p2rank": 0.793291,
                "pocketminer": 0.752297, "plmnn": 0.823469}
    labels = {"p2rank": "P2Rank\nlocal surface",
              "pocketminer": "PocketMiner\nstructure graph",
              "table_field": "deployed\n645 wires",
              "plmnn": "pLM-NN\nwhole sequence"}
    keys = sorted(official, key=lambda m: read["levels"][m] - official[m])
    x = np.arange(len(keys))
    axr.bar(x - 0.19, [official[m] for m in keys], width=0.36, color="#999999",
            zorder=2, label="official CryptoBench test fold")
    axr.bar(x + 0.19, [read["levels"][m] for m in keys], width=0.36,
            color="#7b3294", zorder=2, label="set B + C (cryo-EM)")
    for k, m in enumerate(keys):
        d = read["levels"][m] - official[m]
        axr.annotate(f"{d:+.4f}",
                     (x[k], max(official[m], read["levels"][m]) + 0.006),
                     ha="center", fontsize=8.6,
                     color="#1a6b1a" if d > 0 else "#8b1a1a")
    axr.set_xticks(x)
    axr.set_xticklabels([labels[m] for m in keys], fontsize=8.4)
    axr.set_ylim(0.66, 0.92)
    axr.set_ylabel("mean per-unit ROC-AUC", fontsize=9.4)
    axr.set_xlabel("every method that reads coordinates loses;\n"
                   "the one that reads sequence gains", fontsize=8.8,
                   color="#333333", labelpad=6)
    axr.legend(fontsize=8.3, loc="upper left", frameon=False)
    axr.grid(axis="y", alpha=0.2, lw=0.5)
    axr.set_axisbelow(True)

    fig.tight_layout()
    out = FIGDIR / "fig_setbc_read.png"
    fig.savefig(out, dpi=200)
    plt.close(fig)

    prim = read["co_primary"]["geometry_field_minus_table_field"]
    n = read["coverage"]["n_units_compared"]
    chain = diff["label_geometry"]["set_b_and_c_pooled"]["chain_length"]["median"]
    caption = (
        f"The second external read, taken once on {n} single-particle cryo-EM "
        f"units frozen before the four wire families existed, under a plan "
        f"committed before it. Left: the four comparisons the plan fixed, with "
        f"95 % intervals in bold, the Bonferroni interval over four behind them, "
        f"and the value pinned in the plan as an orange tick. **The comparison "
        f"the read exists for is the top one and it does not resolve**: "
        f"{prim['mean']:+.4f} {prim['ci']}, ahead on {prim['n_first_ahead']} "
        f"units of {n}, on an interval containing both the training-fold "
        f"estimate of {prim['predicted']:+.4f} and its negation. "
        f"{n} units and an effect of this size gave the read limited power, "
        f"which is a statement about the read and not evidence that the lift is "
        f"absent \u2014 nor that it is present. Right: the confound named before "
        f"the read was that these chains, {chain:.0f} residues at the median "
        f"against the official fold's 290, would inflate whichever detector "
        f"reads further, with P2Rank pinned as the control. The control fell by "
        f"0.041 and so did every other coordinate-reading method, while the "
        f"sequence model rose by 0.044. That is a modality effect \u2014 cryo-EM "
        f"coordinates carry less usable local geometry than X-ray at comparable "
        f"nominal resolution \u2014 and it explains the levels in the right panel "
        f"while saying nothing about the difference in the left one, since the "
        f"primary comparison is between two detectors inside one modality.")
    return out, caption


def figure_residue_recoveries(d: dict) -> tuple[Path, str]:
    """Residue recoveries vs mirrors under the RhoA rule, on all of Set A."""
    c = d["counts"]
    fig, ax = plt.subplots(figsize=(6.2, 3.6))
    labels = ["recovered\nresidues", "mirror\nresidues",
              "units with\nrecovery", "units with\nmirror"]
    vals = [c["n_recovered_residues"], c["n_mirror_residues"],
            c["n_units_with_a_recovery"], c["n_units_with_a_mirror"]]
    ax.bar(labels, vals, color=["#1b6b4a", "#8a2b2b", "#1b6b4a", "#8a2b2b"],
           width=0.65)
    for i, v in enumerate(vals):
        ax.text(i, v + 0.3, str(v), ha="center", fontsize=10)
    ax.set_ylabel("count")
    fig.tight_layout()
    out = FIGDIR / "fig_residue_recoveries.png"
    fig.savefig(out, dpi=160)
    plt.close(fig)
    caption = (
        f"Residue-level recoveries against pLM-NN on spent Set A under the rule "
        f"fixed in the RhoA case (labelled cryptic, ours≥"
        f"{d['rule']['ours_percentile_at_least']:.0%}, pLM-NN≤"
        f"{d['rule']['plmnn_percentile_at_most']:.0%}). "
        f"{c['n_recovered_residues']} recovered residues across "
        f"{c['n_units_with_a_recovery']} units; "
        f"{c['n_mirror_residues']} mirror residues across "
        f"{c['n_units_with_a_mirror']} units. The asymmetry favours pLM-NN at "
        f"residue granularity; the panel reports both directions. RhoA and RAC1 "
        f"appear among the recoveries. Mean unit deficit remains −0.0340; "
        f"clinical_grade is false.")
    return out, caption



def figure_dual_baseline_recoveries(d: dict) -> tuple[Path, str]:
    """Residues recovered against both pLM-NN and P2Rank on spent Set A."""
    c = d["counts"]
    fig, ax = plt.subplots(figsize=(6.4, 3.8))
    labels = ["recovered\n(both miss)", "mirror\n(both hit)",
              "units with\nrecovery", "units with\nmirror"]
    vals = [c["n_recovered_residues"], c["n_mirror_residues"],
            c["n_units_with_a_recovery"], c["n_units_with_a_mirror"]]
    ax.bar(labels, vals, color=["#1b6b4a", "#8a2b2b", "#1b6b4a", "#8a2b2b"],
           width=0.65)
    for i, v in enumerate(vals):
        ax.text(i, v + 0.15, str(v), ha="center", fontsize=10)
    ax.set_ylabel("count")
    fig.tight_layout()
    out = FIGDIR / "fig_dual_baseline_recoveries.png"
    fig.savefig(out, dpi=160)
    plt.close(fig)
    caption = (
        f"Dual-baseline residue recoveries on spent Set A: labelled cryptic, "
        f"counting field ≥{d['rule']['ours_percentile_at_least']:.0%}, "
        f"pLM-NN and P2Rank both ≤{d['rule']['plmnn_percentile_at_most']:.0%}. "
        f"{c['n_recovered_residues']} recovered residues across "
        f"{c['n_units_with_a_recovery']} units; "
        f"{c['n_mirror_residues']} mirror residues across "
        f"{c['n_units_with_a_mirror']} units. Asymmetry favours the baselines; "
        f"confirmatory means unchanged. clinical_grade is false.")
    return out, caption


def figure_setn_read(d: dict) -> tuple[Path, str]:
    """Unit-level specificity AUCs on Set A positives vs Set N negatives."""
    auc = d["unit_level_auc"]
    ctrl = float(d["control_chain_length_alone"])
    order = [
        ("pLM-NN", auc["plmnn"], "#8a2b2b"),
        ("PocketMiner", auc["pocketminer"], "#8a2b2b"),
        ("chain length\n(control)", ctrl, "#666666"),
        ("table_field\n(ours)", auc["table_field"], "#1b6b4a"),
        ("P2Rank", auc["p2rank"], "#8a2b2b"),
    ]
    labels = [a[0] for a in order]
    vals = [a[1] for a in order]
    colors = [a[2] for a in order]
    fig, ax = plt.subplots(figsize=(7.2, 3.8))
    ax.bar(labels, vals, color=colors, width=0.7)
    ax.axhline(0.5, color="#333", ls="--", lw=0.8, alpha=0.7)
    for i, v in enumerate(vals):
        ax.text(i, v + 0.008, f"{v:.3f}", ha="center", fontsize=9)
    ax.set_ylabel("unit-level ROC-AUC\n(pos = cryptic pocket, neg = none)")
    ax.set_ylim(0.35, 0.72)
    fig.tight_layout()
    out = FIGDIR / "fig_setn_read.png"
    fig.savefig(out, dpi=160)
    plt.close(fig)
    caption = (
        f"Set N specificity read ({d['n_units_compared']} units: "
        f"{d['n_positive']} with a cryptic pocket, {d['n_negative']} shown to "
        f"have none). Unit score = mean of top-10 residue scores; statistic = "
        f"ROC-AUC separating the halves. Outcome under the committed plan: "
        f"{d['outcome']}. Point estimates: pLM-NN {auc['plmnn']:.4f}, "
        f"PocketMiner {auc['pocketminer']:.4f}, chain-length control {ctrl:.4f}, "
        f"counting field {auc['table_field']:.4f}, P2Rank {auc['p2rank']:.4f}. "
        f"Every Bonferroni-corrected comparison of the counting field against a "
        f"baseline crosses zero. clinical_grade is false.")
    return out, caption


def figure_rhoa_case(d: dict) -> tuple[Path, str]:
    """Cryptic residues of RhoA: counting-field percentile vs pLM-NN percentile."""
    rows = [r for r in d["per_residue"] if r["cryptic"]]
    lo = d["residue_rule"]["ours_percentile_at_least"]
    hi = d["residue_rule"]["plmnn_percentile_at_most"]
    fig, ax = plt.subplots(figsize=(5.6, 5.2))
    ax.scatter([r["plmnn_percentile"] for r in rows],
               [r["ours_percentile"] for r in rows],
               c="#1b6b4a", s=36, zorder=3)
    ax.axhline(lo, color="#1b6b4a", ls="--", lw=0.8, alpha=0.7)
    ax.axvline(hi, color="#8a2b2b", ls="--", lw=0.8, alpha=0.7)
    ax.fill_between([0, hi], lo, 1, color="#1b6b4a", alpha=0.08)
    for r in rows:
        if r["resseq"] in d["recovered_cryptic_residues"]:
            ax.annotate(str(r["resseq"]),
                        (r["plmnn_percentile"], r["ours_percentile"]),
                        textcoords="offset points", xytext=(4, 2),
                        fontsize=8, color="#1b6b4a")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.set_xlabel("pLM-NN within-chain percentile")
    ax.set_ylabel("counting field within-chain percentile")
    ax.set_aspect("equal")
    fig.tight_layout()
    out = FIGDIR / "fig_rhoa_case.png"
    fig.savefig(out, dpi=160)
    plt.close(fig)
    recovered = d["recovered_cryptic_residues"]
    caption = (
        f"RhoA (UniProt P61586, PDB {d['unit']}): each point is one of "
        f"{d['protein']['n_cryptic_residues']} labelled cryptic residues. "
        f"Shaded region: counting field ≥{lo:.0%} of the chain and pLM-NN "
        f"≤{hi:.0%}. Residues {recovered} meet the rule; the mirror is empty. "
        f"Residue 30 is ours {d['headline_residue']['ours_percentile']:.1%} vs "
        f"pLM-NN {d['headline_residue']['plmnn_percentile']:.1%}. Unit-level "
        f"ROC-AUC is {d['unit_level_auc']['table_field']:.3f} against "
        f"{d['unit_level_auc']['plmnn']:.3f}. Spent external set; not a second "
        f"confirmatory read; clinical_grade is false.")
    return out, caption


def figure_geometry_vs_plmnn_by_length(d: dict) -> tuple[Path, str]:
    """Length strata of geometry_field vs pLM-NN on the official fold."""
    import numpy as np
    bins = d["length_bins"]
    labels = [b["bin"] for b in bins]
    geo = [b["mean_geometry"] for b in bins]
    plm = [b["mean_plmnn"] for b in bins]
    fig, ax = plt.subplots(figsize=(6.2, 3.8))
    x = np.arange(len(labels))
    w = 0.35
    ax.bar(x - w / 2, geo, w, label="geometry_field", color="#1b6b4a")
    ax.bar(x + w / 2, plm, w, label="pLM-NN", color="#8a2b2b")
    for i, b in enumerate(bins):
        ax.text(i, max(geo[i], plm[i]) + 0.008,
                f"Δ={b['mean_delta']:+.3f}\nn={b['n_units']}",
                ha="center", fontsize=8)
    ax.set_xticks(x)
    ax.set_xticklabels(labels)
    ax.set_ylabel("mean per-unit ROC-AUC")
    ax.set_ylim(0.70, 0.95)
    ax.legend(frameon=False)
    ax.set_title("Official fold: geometry_field vs pLM-NN by chain length")
    fig.tight_layout()
    out = FIGDIR / "fig_geometry_vs_plmnn_by_length.png"
    fig.savefig(out, dpi=160)
    plt.close(fig)
    long = next(b for b in bins if b["bin"] == "n>=300")
    short = next(b for b in bins if b["bin"] == "n<150")
    lo, hi = long["ci95_delta"]
    slo, shi = short["ci95_delta"]
    caption = (
        f"Official CryptoBench test fold stratified by chain length: mean "
        f"per-unit ROC-AUC for geometry_field vs pLM-NN. On n≥300 "
        f"({long['n_units']} units) the point estimate leads "
        f"({long['mean_geometry']:.4f} vs {long['mean_plmnn']:.4f}, "
        f"Δ={long['mean_delta']:+.4f} [{lo:+.4f}, {hi:+.4f}], ahead "
        f"{long['n_geometry_ahead']}/{long['n_plmnn_ahead']}); the CI still "
        f"crosses zero. Short chains (n<150, {short['n_units']} units) sit the "
        f"other way (Δ={short['mean_delta']:+.4f} [{slo:+.4f}, {shi:+.4f}]). "
        f"Fold-mean parity is unchanged. Development stratification; "
        f"clinical_grade is false.")
    return out, caption


def figure_geometry_field_vs_plmnn(d: dict) -> tuple[Path, str]:
    """Official-fold development probe: geometry_field vs pLM-NN per unit.

    Not confirmatory — the fold has been read many times. Caption states parity
    (CI crosses zero) and names the detectors so this is not confused with the
    table_field deficit of −0.0243.
    """
    import numpy as np
    rows = d["units_sorted_by_delta"]
    deltas = np.array([r["delta"] for r in rows])
    fig, ax = plt.subplots(figsize=(7.4, 4.4))
    colors = ["#1b6b4a" if v > 0 else "#8a2b2b" for v in deltas]
    ax.barh(range(len(deltas)), deltas[::-1], color=colors[::-1], height=0.85)
    ax.axvline(0, color="black", lw=0.8)
    lo, hi = d["ci95_delta"]
    ax.set_xlabel("per-unit ROC-AUC: geometry_field − pLM-NN")
    ax.set_yticks([])
    ax.set_title(
        f"mean {d['mean_geometry_field']:.4f} vs {d['mean_plmnn']:.4f}; "
        f"Δ={d['mean_delta_geometry_minus_plmnn']:+.4f} "
        f"[{lo:+.4f}, {hi:+.4f}]")
    fig.tight_layout()
    out = FIGDIR / "fig_geometry_field_vs_plmnn_official.png"
    fig.savefig(out, dpi=160)
    plt.close(fig)
    caption = (
        f"Development probe on the official CryptoBench test fold "
        f"({d['n_units_compared']} units): per-unit ROC-AUC difference "
        f"geometry_field − pLM-NN, sorted. Mean levels "
        f"{d['mean_geometry_field']:.4f} vs {d['mean_plmnn']:.4f}; "
        f"paired Δ={d['mean_delta_geometry_minus_plmnn']:+.4f} "
        f"[{lo:+.4f}, {hi:+.4f}] (crosses zero → parity, not a resolved win). "
        f"Ahead on {d['n_geometry_ahead']} units, behind on {d['n_plmnn_ahead']}. "
        f"The published table_field level on this fold is 0.7992 "
        f"(Δ vs pLM-NN −0.0243). Not confirmatory; clinical_grade is false.")
    return out, caption


def figure_where_we_beat_plmnn(d: dict) -> tuple[Path, str]:
    """Every Set A unit's delta against pLM-NN, with the clear-margin bar marked.

    The confirmatory read already said 27 units favour us and 30 favour them, and
    that the mean is −0.0340. This panel is that split made visible: each bar is
    one unit, green clears a fixed margin (≥0.10 and ours≥0.85), red is the mirror.
    RhoA (9n4c_A) is labelled because its accession is in the frozen set; the mean
    is still a deficit and the caption says so.
    """
    import numpy as np
    rows = d["all_units_sorted_by_ours_minus_plmnn"]
    deltas = np.array([r["ours_minus_plmnn"] for r in rows])
    clear = d["clear_margin_rule"]["ours_minus_plmnn_at_least"]
    colors = ["#1b6b4a" if v >= clear else ("#8a2b2b" if v <= -clear else "#9a9a9a")
              for v in deltas]
    fig, ax = plt.subplots(figsize=(7.4, 4.4))
    ax.barh(range(len(deltas)), deltas[::-1], color=colors[::-1], height=0.85)
    ax.axvline(0, color="black", lw=0.8)
    ax.axvline(clear, color="#1b6b4a", ls="--", lw=0.8, alpha=0.75)
    ax.axvline(-clear, color="#8a2b2b", ls="--", lw=0.8, alpha=0.75)
    ax.set_xlabel("per-unit ROC-AUC: counting field − pLM-NN")
    ax.set_yticks([])
    by = {r["unit"]: i for i, r in enumerate(rows)}
    for r in d.get("named_oncology_gtpases_in_the_clear_margin") or []:
        i = by[r["unit"]]
        ax.annotate(
            f"{r['unit']} RhoA",
            xy=(r["ours_minus_plmnn"], len(rows) - 1 - i),
            xytext=(4, 0), textcoords="offset points", fontsize=8,
            color="#1b6b4a", va="center")
    fig.tight_layout()
    out = FIGDIR / "fig_external_beat_plmnn.png"
    fig.savefig(out, dpi=160)
    plt.close(fig)
    n_c = d["clear_margin_rule"]["n_clear_margin"]
    n_m = d["clear_margin_rule"]["n_clear_margin_mirror"]
    caption = (
        f"Per-unit ROC-AUC difference against pLM-NN on the 57 spent external "
        f"units, sorted. Green bars clear a fixed margin "
        f"(Δ≥{clear:.2f} and ours≥{d['clear_margin_rule']['ours_at_least']}); "
        f"red bars are the mirror. {n_c} clear-margin wins for the counting field, "
        f"{n_m} for pLM-NN. The confirmatory mean remains −0.0340 — this panel "
        f"names the 27/30 split already published, it does not reverse it. "
        f"RhoA (P61586, 9n4c_A) is one clear-margin unit; nothing here is clinical.")
    return out, caption


def main() -> int:
    FIGDIR.mkdir(exist_ok=True)
    boot = json.loads(BOOT.read_text())
    led = json.loads(LEDGER.read_text())
    drawn = [figure_metrics(boot), figure_paired(boot, led)]
    if PREREG_READ.exists():
        drawn.append(figure_functionals(json.loads(PREREG_READ.read_text())))
    if MATCH_READ.exists():
        drawn.append(figure_matched(json.loads(MATCH_READ.read_text())))
    if FULL_READ.exists():
        drawn.append(figure_full_metrics(json.loads(FULL_READ.read_text())))
    if SUBGROUP_READ.exists():
        drawn.append(figure_subgroups(json.loads(SUBGROUP_READ.read_text())))
    if CURVE.exists():
        drawn.append(figure_threshold_curve(json.loads(CURVE.read_text())))
    if CASES.exists():
        drawn.append(figure_cases(json.loads(CASES.read_text())))
        if AUDIT.exists():
            drawn.append(figure_structural_cases(
                json.loads(CASES.read_text()), json.loads(AUDIT.read_text())))
    if DIFFICULTY.exists():
        drawn.append(figure_external_difficulty(
            json.loads(DIFFICULTY.read_text())))
    if SETBC_READ.exists() and SETBC_DIFF.exists():
        # SETBC_DIFF, not DIFFICULTY: the first pass passed Set A's difficulty
        # artifact to the Set B/C figure and raised on a missing key. Two
        # artifacts with near-identical shapes and different subjects is exactly
        # where that happens.
        drawn.append(figure_setbc_read(json.loads(SETBC_READ.read_text()),
                                       json.loads(SETBC_DIFF.read_text())))
    if EMDB.exists():
        got = figure_emdb_resolution()
        if got is not None:
            drawn.append(got)
    if WHERE_WE.exists():
        drawn.append(figure_where_we_beat_plmnn(json.loads(WHERE_WE.read_text())))
    if RHOA.exists():
        drawn.append(figure_rhoa_case(json.loads(RHOA.read_text())))
    if RESIDUE_REC.exists():
        drawn.append(figure_residue_recoveries(json.loads(RESIDUE_REC.read_text())))
    if DUAL_REC.exists():
        drawn.append(figure_dual_baseline_recoveries(json.loads(DUAL_REC.read_text())))
    if SETN_READ.exists():
        drawn.append(figure_setn_read(json.loads(SETN_READ.read_text())))
    if GEOM_PROBE.exists():
        drawn.append(figure_geometry_field_vs_plmnn(
            json.loads(GEOM_PROBE.read_text())))
    if GEOM_LEN.exists():
        drawn.append(figure_geometry_vs_plmnn_by_length(
            json.loads(GEOM_LEN.read_text())))
    images = [p for p, _ in drawn]
    for out in images:
        print(f"wrote {out.relative_to(ROOT)} "
              f"({out.stat().st_size / 1e3:.0f} kB)")
    if not _write_readme(drawn):
        return 1
    print(f"wrote the figure block in {README.relative_to(ROOT)}")

    # Naming the generator is not enough: an image keeps its filename while the
    # numbers underneath it move, and a stale plot passes a name check silently.
    # Recording what each image was drawn from lets the gate fail on the source
    # digest, which is the drift that matters and does not need a plotting
    # library in CI to detect.
    PROVENANCE.write_text(json.dumps({
        "schema": "geoaudit.figure_provenance.v1",
        "clinical_grade": False,
        "purpose": "tie every committed image to the exact bytes it was drawn "
                   "from, so a figure cannot outlive the numbers it shows",
        "generator": "tools/make_official_figures.py",
        "sources": {str(p.relative_to(ROOT)): _sha(p)
                    for p in SOURCES if p.exists()},
        "figures": {p.name: {"sha256": _sha(p), "bytes": p.stat().st_size,
                             "caption": c}
                    for p, c in drawn},
    }, indent=2) + "\n")
    print(f"wrote {PROVENANCE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
