#!/usr/bin/env python3.12
"""Record this repository's visibility by running the command, not by typing it.

The candidate-showcase exception in ``tools/verify_claims.py`` is granted on one
premise: that the repository is private, so nothing in it is a publication and
no prior art is created against a composition claim. That premise is a fact
about a remote server which can change without any commit, and it was believed
here once with a real consequence.

``contracts/CANDIDATE_SHOWCASES.json`` carried::

    "repository_visibility_confirmed_at": {
      "checked": "2026-07-31",
      "result": "private",
      "how": "gh repo view shaneraphel/geoaudit-cryptobench --json isPrivate"
    }

The command it names returns ``isPrivate: false``. It appears never to have
returned anything else: the repository's ``CreateEvent`` sits in GitHub's public
events timeline at 2026-07-05T04:49:13Z with continuous public pushes through
2026-08-03, and that timeline does not carry events from private repositories.
The field had the form of a verified fact -- it cited its own command -- and the
recorded result was the opposite of what the command returns. Six candidate
compositions were disclosed worldwide while every gate above it passed.

Hence this tool. The visibility record is generated by inspection, the way
``ENVIRONMENT.json`` is, and ``make verify`` reads the generated value. Two
independent signals are recorded because they fail differently:

``api``
    ``gh repo view --json isPrivate``. Authoritative and current, but it is a
    single call whose result is exactly what was mis-transcribed before.

``public_timeline``
    whether GitHub's public events API returns events for the repository.
    Private-repository events do not appear there, so any event is positive
    evidence of public exposure *at the time of that event* -- which is the
    question a filing decision actually asks, and one the point-in-time API
    call cannot answer. An empty timeline is weak evidence of privacy, since
    events also age out, and the tool says so rather than reading it as private.

Disagreement between the two is not resolved here. It is recorded and the
result is ``"indeterminate"``, which the gate treats as not-private.

Usage::

    python3.12 tools/record_repository_visibility.py [--slug OWNER/NAME]

Writes ``repository_visibility_confirmed_at`` into
``contracts/CANDIDATE_SHOWCASES.json`` and prints the result. Exits non-zero if
the commands cannot be run, so that an unreachable network records "unknown"
rather than silently leaving a stale "private" in place.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "contracts/CANDIDATE_SHOWCASES.json"
DEFAULT_SLUG = "shaneraphel/geoaudit-cryptobench"


def _run(args: list[str]) -> tuple[int, str, str]:
    proc = subprocess.run(args, capture_output=True, text=True, timeout=120)
    return proc.returncode, proc.stdout.strip(), proc.stderr.strip()


def probe(slug: str) -> dict:
    """Both signals, with the exact command and the exact failure text."""
    record: dict = {
        "schema": "geoaudit.repository_visibility.v1",
        "slug": slug,
        "checked_at": dt.datetime.now(dt.timezone.utc).isoformat(
            timespec="seconds"),
        "why_generated": (
            "a hand-written 'result: private' in this field was false on the "
            "day it was written and six candidate compositions were published "
            "under it. The premise of an irreversible exception is established "
            "by running the command, never by recording that it was run"),
    }
    if shutil.which("gh") is None:
        record["api"] = {
            "ok": False,
            "how": "gh repo view",
            "error": "gh is not on PATH",
        }
        record["public_timeline"] = {
            "ok": False, "error": "gh is not on PATH"}
        record["result"] = "unknown"
        record["why_that_result"] = (
            "the check could not run. 'unknown' is not 'private': the gate "
            "withholds the exception, which is the safe direction because the "
            "hazard it guards is irreversible")
        return record

    how_api = ["gh", "repo", "view", slug, "--json", "isPrivate,visibility"]
    rc, out, err = _run(how_api)
    api: dict = {"ok": rc == 0, "how": " ".join(how_api)}
    if rc == 0:
        try:
            payload = json.loads(out)
            api["is_private"] = bool(payload.get("isPrivate"))
            api["visibility"] = payload.get("visibility")
        except Exception as exc:  # noqa: BLE001
            api["ok"] = False
            api["error"] = f"unparseable response: {exc}: {out[:200]}"
    else:
        api["error"] = err[:400] or f"exit {rc}"
    record["api"] = api

    how_ev = ["gh", "api", f"repos/{slug}/events", "--paginate"]
    rc, out, err = _run(how_ev)
    timeline: dict = {
        "ok": rc == 0,
        "how": " ".join(how_ev),
        "what_it_means": (
            "GitHub's public events timeline does not carry events from "
            "private repositories, so any event here is positive evidence the "
            "repository was public at that event's timestamp. An empty "
            "timeline is only weak evidence of privacy, because events also "
            "age out of the window"),
    }
    if rc == 0:
        try:
            events = json.loads(out) if out else []
            stamps = sorted(e.get("created_at", "") for e in events
                            if e.get("created_at"))
            timeline["n_public_events"] = len(events)
            timeline["earliest_public_event"] = stamps[0] if stamps else None
            timeline["latest_public_event"] = stamps[-1] if stamps else None
        except Exception as exc:  # noqa: BLE001
            timeline["ok"] = False
            timeline["error"] = f"unparseable response: {exc}"
    else:
        timeline["error"] = err[:400] or f"exit {rc}"
    record["public_timeline"] = timeline

    # Resolution. Public wins over private from either signal, because a false
    # "private" is the failure with the irreversible consequence and a false
    # "public" only costs an exception we can re-earn.
    api_says_public = api.get("ok") and api.get("is_private") is False
    api_says_private = api.get("ok") and api.get("is_private") is True
    timeline_says_public = bool(timeline.get("n_public_events"))
    if api_says_public or timeline_says_public:
        record["result"] = "public"
        record["why_that_result"] = (
            f"api is_private={api.get('is_private')!r}; public timeline holds "
            f"{timeline.get('n_public_events')} event(s) from "
            f"{timeline.get('earliest_public_event')} to "
            f"{timeline.get('latest_public_event')}. Either signal alone is "
            f"enough to withhold the exception")
    elif api_says_private and not timeline_says_public:
        record["result"] = "private"
        record["why_that_result"] = (
            "the api reports private and the public events timeline is empty. "
            "The exception is available; it is still bounded by the caps and "
            "the field-completeness rules in this registry")
    else:
        record["result"] = "indeterminate"
        record["why_that_result"] = (
            "the two signals did not agree or could not be read. Treated as "
            "not-private by the gate")
    return record


def build(slug: str = DEFAULT_SLUG) -> dict:
    record = probe(slug)
    registry = json.loads(REGISTRY.read_text())
    registry["repository_visibility_confirmed_at"] = record
    REGISTRY.write_text(json.dumps(registry, indent=2) + "\n")
    return record


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--slug", default=DEFAULT_SLUG)
    args = ap.parse_args()
    record = build(args.slug)
    print(f"visibility: {record['result']}")
    print(f"  api: {record.get('api', {})}")
    tl = record.get("public_timeline", {})
    print(f"  public events: {tl.get('n_public_events')} "
          f"({tl.get('earliest_public_event')} .. "
          f"{tl.get('latest_public_event')})")
    print(f"  written to {REGISTRY.relative_to(ROOT)}")
    return 0 if record["result"] in {"public", "private"} else 1


if __name__ == "__main__":
    raise SystemExit(main())
